%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(activity_pb).
-define(activity_pb, true).

-define(activity_pb_gpb_version, "4.18.0").

-ifndef('ACTIVITY_PB_H').
-define('ACTIVITY_PB_H', true).
-record('Activity',
        {id                     :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         player_id              :: non_neg_integer() | undefined, % = 2, required, 64 bits
         f3                     :: non_neg_integer() | undefined, % = 3, required, 32 bits
         name                   :: unicode:chardata() | undefined, % = 4, required
         f5                     :: non_neg_integer() | undefined, % = 5, optional, 32 bits
         f6                     :: non_neg_integer() | undefined, % = 6, optional, 32 bits
         start_date             :: unicode:chardata() | undefined, % = 7, required
         end_date               :: unicode:chardata() | undefined, % = 8, optional
         distance               :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 9, optional
         avg_heart_rate         :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 10, optional
         max_heart_rate         :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 11, optional
         avg_watts              :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 12, optional
         max_watts              :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 13, optional
         avg_cadence            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 14, optional
         max_cadence            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 15, optional
         avg_speed              :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 16, optional
         max_speed              :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 17, optional
         calories               :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 18, optional
         total_elevation        :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 19, optional
         strava_upload_id       :: non_neg_integer() | undefined, % = 20, optional, 64 bits
         strava_activity_id     :: non_neg_integer() | undefined, % = 21, optional, 64 bits
         f23                    :: non_neg_integer() | undefined, % = 23, optional, 32 bits
         fit                    :: iodata() | undefined, % = 24, optional
         fit_filename           :: unicode:chardata() | undefined, % = 25, optional
         f29                    :: non_neg_integer() | undefined, % = 29, optional, 32 bits
         date                   :: unicode:chardata() | undefined % = 31, optional
        }).
-endif.

-ifndef('ACTIVITIES_PB_H').
-define('ACTIVITIES_PB_H', true).
-record('Activities',
        {activities = []        :: [activity_pb:'Activity'()] | undefined % = 1, repeated
        }).
-endif.

-endif.
