%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(events_pb).
-define(events_pb, true).

-define(events_pb_gpb_version, "4.18.0").

-ifndef('CATEGORY_PB_H').
-define('CATEGORY_PB_H', true).
-record('Category',
        {id                     :: non_neg_integer() | undefined, % = 1, required, 64 bits
         description            :: unicode:chardata() | undefined, % = 2, optional
         f3                     :: unicode:chardata() | undefined, % = 3, optional
         f5                     :: non_neg_integer() | undefined, % = 5, optional, 32 bits
         f6                     :: non_neg_integer() | undefined, % = 6, optional, 32 bits
         f7                     :: unicode:chardata() | undefined, % = 7, optional
         rules_id               :: non_neg_integer() | undefined, % = 8, optional, 32 bits
         registrationStart      :: non_neg_integer() | undefined, % = 9, optional, 64 bits
         registrationStartWT    :: non_neg_integer() | undefined, % = 10, optional, 64 bits
         registrationEnd        :: non_neg_integer() | undefined, % = 11, optional, 64 bits
         registrationEndWT      :: non_neg_integer() | undefined, % = 12, optional, 64 bits
         lineUpStart            :: non_neg_integer() | undefined, % = 13, optional, 64 bits
         lineUpStartWT          :: non_neg_integer() | undefined, % = 14, optional, 64 bits
         lineUpEnd              :: non_neg_integer() | undefined, % = 15, optional, 64 bits
         lineUpEndWT            :: non_neg_integer() | undefined, % = 16, optional, 64 bits
         eventSubgroupStart     :: non_neg_integer() | undefined, % = 17, optional, 64 bits
         eventSubgroupStartWT   :: non_neg_integer() | undefined, % = 18, optional, 64 bits
         f21                    :: non_neg_integer() | undefined, % = 21, optional, 32 bits
         route_id               :: non_neg_integer() | undefined, % = 22, required, 64 bits
         leaders = []           :: [non_neg_integer()] | undefined, % = 23, repeated, 32 bits
         f24                    :: non_neg_integer() | undefined, % = 24, optional, 32 bits
         laps                   :: non_neg_integer() | undefined, % = 25, optional, 32 bits
         startLocation          :: non_neg_integer() | undefined, % = 29, optional, 32 bits
         label                  :: non_neg_integer() | undefined, % = 30, optional, 32 bits
         f31                    :: non_neg_integer() | undefined, % = 31, optional, 32 bits
         f32                    :: non_neg_integer() | undefined, % = 32, optional, 32 bits
         f33                    :: non_neg_integer() | undefined, % = 33, optional, 32 bits
         duration               :: non_neg_integer() | undefined, % = 34, optional, 32 bits
         f36                    :: non_neg_integer() | undefined, % = 36, optional, 64 bits
         f37                    :: non_neg_integer() | undefined, % = 37, optional, 32 bits
         audio                  :: unicode:chardata() | undefined, % = 39, optional
         sweepers = []          :: [non_neg_integer()] | undefined, % = 41, repeated, 32 bits
         f43                    :: unicode:chardata() | undefined, % = 43, optional
         f44                    :: non_neg_integer() | undefined, % = 44, optional, 32 bits
         tags                   :: unicode:chardata() | undefined, % = 45, optional
         lateJoinInMinutes      :: non_neg_integer() | undefined, % = 46, optional, 32 bits
         map_id                 :: non_neg_integer() | undefined % = 47, optional, 32 bits
        }).
-endif.

-ifndef('EVENT_PB_H').
-define('EVENT_PB_H', true).
-record('Event',
        {id                     :: non_neg_integer() | undefined, % = 1, required, 64 bits
         world_id               :: non_neg_integer() | undefined, % = 2, optional, 32 bits
         title                  :: unicode:chardata() | undefined, % = 3, required
         description            :: unicode:chardata() | undefined, % = 4, optional
         eventStart             :: non_neg_integer() | undefined, % = 5, optional, 64 bits
         f7                     :: non_neg_integer() | undefined, % = 7, optional, 32 bits
         laps                   :: non_neg_integer() | undefined, % = 8, optional, 64 bits
         f9                     :: non_neg_integer() | undefined, % = 9, optional, 64 bits
         category = []          :: [events_pb:'Category'()] | undefined, % = 10, repeated
         f11                    :: unicode:chardata() | undefined, % = 11, optional
         pic_url                :: unicode:chardata() | undefined, % = 12, optional
         duration               :: non_neg_integer() | undefined, % = 13, optional, 32 bits
         route_id               :: non_neg_integer() | undefined, % = 14, optional, 64 bits
         rules_id               :: non_neg_integer() | undefined, % = 15, optional, 64 bits
         f16                    :: non_neg_integer() | undefined, % = 16, optional, 64 bits
         f17                    :: non_neg_integer() | undefined, % = 17, optional, 64 bits
         f18                    :: non_neg_integer() | undefined, % = 18, optional, 64 bits
         f19                    :: unicode:chardata() | undefined, % = 19, optional
         f22                    :: non_neg_integer() | undefined, % = 22, optional, 32 bits
         f24                    :: non_neg_integer() | undefined, % = 24, optional, 32 bits
         f26                    :: unicode:chardata() | undefined, % = 26, optional
         f27                    :: non_neg_integer() | undefined, % = 27, optional, 32 bits
         f28                    :: non_neg_integer() | undefined, % = 28, optional, 32 bits
         f29                    :: non_neg_integer() | undefined, % = 29, optional, 32 bits
         tags                   :: unicode:chardata() | undefined, % = 31, optional
         lateJoinInMinutes      :: non_neg_integer() | undefined, % = 34, optional, 32 bits
         map_id                 :: non_neg_integer() | undefined % = 35, optional, 32 bits
        }).
-endif.

-ifndef('EVENTS_PB_H').
-define('EVENTS_PB_H', true).
-record('Events',
        {events = []            :: [events_pb:'Event'()] | undefined % = 1, repeated
        }).
-endif.

-endif.
