%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(goal_pb).
-define(goal_pb, true).

-define(goal_pb_gpb_version, "4.18.0").

-ifndef('GOAL_PB_H').
-define('GOAL_PB_H', true).
-record('Goal',
        {id                     :: non_neg_integer() | undefined, % = 1, optional, 64 bits
         player_id              :: non_neg_integer() | undefined, % = 2, optional, 64 bits
         f3                     :: non_neg_integer() | undefined, % = 3, optional, 32 bits
         name                   :: unicode:chardata() | undefined, % = 4, optional
         type                   :: non_neg_integer() | undefined, % = 5, optional, 32 bits
         periodicity            :: non_neg_integer() | undefined, % = 6, optional, 32 bits
         target_distance        :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 7, optional
         target_duration        :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 8, optional
         actual_distance        :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 9, optional
         actual_duration        :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 10, optional
         created_on             :: non_neg_integer() | undefined, % = 11, optional, 64 bits
         period_end_date        :: non_neg_integer() | undefined, % = 12, optional, 64 bits
         f13                    :: non_neg_integer() | undefined % = 13, optional, 64 bits
        }).
-endif.

-ifndef('GOALS_PB_H').
-define('GOALS_PB_H', true).
-record('Goals',
        {goals = []             :: [goal_pb:'Goal'()] | undefined % = 1, repeated
        }).
-endif.

-endif.
