%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef('hash-seeds_pb').
-define('hash-seeds_pb', true).

-define('hash-seeds_pb_gpb_version', "4.18.0").

-ifndef('HASHSEED_PB_H').
-define('HASHSEED_PB_H', true).
-record('HashSeed',
        {seed1                  :: non_neg_integer() | undefined, % = 1, required, 64 bits
         seed2                  :: non_neg_integer() | undefined, % = 2, required, 64 bits
         expiryDate             :: non_neg_integer() | undefined % = 3, required, 64 bits
        }).
-endif.

-ifndef('HASHSEEDS_PB_H').
-define('HASHSEEDS_PB_H', true).
-record('HashSeeds',
        {seeds = []             :: ['hash-seeds_pb':'HashSeed'()] | undefined % = 1, repeated
        }).
-endif.

-endif.
