%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef('login-response_pb').
-define('login-response_pb', true).

-define('login-response_pb_gpb_version', "4.18.0").

-ifndef('UDPNODE_PB_H').
-define('UDPNODE_PB_H', true).
-record('UDPNode',
        {ip                     :: unicode:chardata() | undefined, % = 1, required
         port                   :: non_neg_integer() | undefined % = 2, required, 32 bits
        }).
-endif.

-ifndef('UDPNODES_PB_H').
-define('UDPNODES_PB_H', true).
-record('UDPNodes',
        {node = []              :: ['login-response_pb':'UDPNode'()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('APIS_PB_H').
-define('APIS_PB_H', true).
-record('APIs',
        {todaysplan_url         :: unicode:chardata() | undefined, % = 1, optional
         trainingpeaks_url      :: unicode:chardata() | undefined % = 2, optional
        }).
-endif.

-ifndef('SERVERINFO_PB_H').
-define('SERVERINFO_PB_H', true).
-record('ServerInfo',
        {relay_url              :: unicode:chardata() | undefined, % = 1, required
         apis                   :: 'login-response_pb':'APIs'() | undefined, % = 2, required
         time                   :: non_neg_integer() | undefined, % = 3, required, 64 bits
         nodes                  :: 'login-response_pb':'UDPNodes'() | undefined % = 4, optional
        }).
-endif.

-ifndef('LOGINRESPONSE_PB_H').
-define('LOGINRESPONSE_PB_H', true).
-record('LoginResponse',
        {session_state          :: unicode:chardata() | undefined, % = 1, required
         info                   :: 'login-response_pb':'ServerInfo'() | undefined % = 2, required
        }).
-endif.

-endif.
