%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef('per-session-info_pb').
-define('per-session-info_pb', true).

-define('per-session-info_pb_gpb_version', "4.18.0").

-ifndef('PERSESSIONINFO_PB_H').
-define('PERSESSIONINFO_PB_H', true).
-record('PerSessionInfo',
        {relay_url              :: unicode:chardata() | undefined % = 1, required
        }).
-endif.

-endif.
