%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef('periodic-info_pb').
-define('periodic-info_pb', true).

-define('periodic-info_pb_gpb_version', "4.18.0").

-ifndef('PERIODICINFO_PB_H').
-define('PERIODICINFO_PB_H', true).
-record('PeriodicInfo',
        {game_server_ip         :: unicode:chardata() | undefined, % = 1, required
         f2                     :: non_neg_integer() | undefined, % = 2, optional, 32 bits
         f3                     :: non_neg_integer() | undefined, % = 3, optional, 32 bits
         f4                     :: non_neg_integer() | undefined, % = 4, optional, 32 bits
         f5                     :: non_neg_integer() | undefined, % = 5, optional, 32 bits
         f6                     :: non_neg_integer() | undefined % = 6, optional, 32 bits
        }).
-endif.

-ifndef('PERIODICINFOS_PB_H').
-define('PERIODICINFOS_PB_H', true).
-record('PeriodicInfos',
        {infos = []             :: ['periodic-info_pb':'PeriodicInfo'()] | undefined % = 1, repeated
        }).
-endif.

-endif.
