%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(profile_pb).
-define(profile_pb, true).

-define(profile_pb_gpb_version, "4.18.0").

-ifndef('PROFILE.PROFILESOCIALFACTS_PB_H').
-define('PROFILE.PROFILESOCIALFACTS_PB_H', true).
-record('Profile.ProfileSocialFacts',
        {profile_id             :: integer() | undefined, % = 1, optional, 64 bits
         f2                     :: integer() | undefined, % = 2, optional, 64 bits
         f3                     :: integer() | undefined, % = 3, optional, 64 bits
         f4                     :: integer() | undefined, % = 4, optional, 64 bits
         f5                     :: 'FOLLOWSTATUS0' | 'SELF' | 'FOLLOWSTATUS2' | 'FOLLOWSTATUS3' | 'FOLLOWSTATUS4' | integer() | undefined, % = 5, optional, enum ProfileFollowStatus
         f6                     :: 'FOLLOWSTATUS0' | 'SELF' | 'FOLLOWSTATUS2' | 'FOLLOWSTATUS3' | 'FOLLOWSTATUS4' | integer() | undefined, % = 6, optional, enum ProfileFollowStatus
         f7                     :: boolean() | 0 | 1 | undefined % = 7, optional
        }).
-endif.

-ifndef('PROFILE_PB_H').
-define('PROFILE_PB_H', true).
-record('Profile',
        {id                     :: integer() | undefined, % = 1, optional, 64 bits
         is_connected_to_strava :: integer() | undefined, % = 2, optional, 32 bits
         email                  :: unicode:chardata() | undefined, % = 3, optional
         first_name             :: unicode:chardata() | undefined, % = 4, optional
         last_name              :: unicode:chardata() | undefined, % = 5, optional
         is_male                :: boolean() | 0 | 1 | undefined, % = 6, optional
         f7                     :: iodata() | undefined, % = 7, optional
         weight_in_grams        :: non_neg_integer() | undefined, % = 9, optional, 32 bits
         ftp                    :: non_neg_integer() | undefined, % = 10, optional, 32 bits
         f11                    :: non_neg_integer() | undefined, % = 11, optional, 32 bits
         f12                    :: non_neg_integer() | undefined, % = 12, optional, 32 bits
         f13                    :: non_neg_integer() | undefined, % = 13, optional, 32 bits
         f14                    :: non_neg_integer() | undefined, % = 14, optional, 32 bits
         f15                    :: non_neg_integer() | undefined, % = 15, optional, 32 bits
         f16                    :: non_neg_integer() | undefined, % = 16, optional, 32 bits
         f17                    :: non_neg_integer() | undefined, % = 17, optional, 32 bits
         f18                    :: non_neg_integer() | undefined, % = 18, optional, 32 bits
         f19                    :: non_neg_integer() | undefined, % = 19, optional, 32 bits
         f20                    :: non_neg_integer() | undefined, % = 20, optional, 32 bits
         f21                    :: non_neg_integer() | undefined, % = 21, optional, 32 bits
         f22                    :: non_neg_integer() | undefined, % = 22, optional, 32 bits
         f23                    :: non_neg_integer() | undefined, % = 23, optional, 32 bits
         f24                    :: non_neg_integer() | undefined, % = 24, optional, 32 bits
         f25                    :: non_neg_integer() | undefined, % = 25, optional, 32 bits
         f26                    :: non_neg_integer() | undefined, % = 26, optional, 32 bits
         f27                    :: non_neg_integer() | undefined, % = 27, optional, 64 bits
         f28                    :: non_neg_integer() | undefined, % = 28, optional, 64 bits
         f29                    :: non_neg_integer() | undefined, % = 29, optional, 64 bits
         f30                    :: non_neg_integer() | undefined, % = 30, optional, 64 bits
         f31                    :: non_neg_integer() | undefined, % = 31, optional, 64 bits
         f32                    :: non_neg_integer() | undefined, % = 32, optional, 64 bits
         f33                    :: iodata() | undefined, % = 33, optional
         country_code           :: non_neg_integer() | undefined, % = 34, optional, 32 bits
         total_distance_in_meters :: non_neg_integer() | undefined, % = 35, optional, 32 bits
         elevation_gain_in_meters :: non_neg_integer() | undefined, % = 36, optional, 32 bits
         time_ridden_in_minutes :: non_neg_integer() | undefined, % = 37, optional, 32 bits
         f38                    :: non_neg_integer() | undefined, % = 38, optional, 32 bits
         f39                    :: non_neg_integer() | undefined, % = 39, optional, 32 bits
         f40                    :: non_neg_integer() | undefined, % = 40, optional, 32 bits
         total_watt_hours       :: non_neg_integer() | undefined, % = 41, optional, 32 bits
         height_in_millimeters  :: non_neg_integer() | undefined, % = 42, optional, 32 bits
         dob                    :: unicode:chardata() | undefined, % = 43, optional
         f44                    :: non_neg_integer() | undefined, % = 44, optional, 32 bits
         f45                    :: boolean() | 0 | 1 | undefined, % = 45, optional
         total_xp               :: non_neg_integer() | undefined, % = 46, optional, 32 bits
         f47                    :: non_neg_integer() | undefined, % = 47, optional, 32 bits
         player_type            :: 'PLAYERTYPE0' | 'NORMAL' | 'PLAYERTYPE2' | 'PLAYERTYPE3' | 'PLAYERTYPE4' | integer() | undefined, % = 48, optional, enum Profile.PlayerType
         achievement_level      :: non_neg_integer() | undefined, % = 49, optional, 32 bits
         f50                    :: boolean() | 0 | 1 | undefined, % = 50, optional
         f51                    :: boolean() | 0 | 1 | undefined, % = 51, optional
         f52                    :: non_neg_integer() | undefined, % = 52, optional, 32 bits
         f53                    :: non_neg_integer() | undefined, % = 53, optional, 32 bits
         f54                    :: non_neg_integer() | undefined, % = 54, optional, 32 bits
         age                    :: non_neg_integer() | undefined, % = 55, optional, 32 bits
         f56                    :: non_neg_integer() | undefined, % = 56, optional, 32 bits
         f57                    :: non_neg_integer() | undefined, % = 57, optional, 32 bits
         f58                    :: iodata() | undefined, % = 58, optional
         f59                    :: non_neg_integer() | undefined, % = 59, optional, 64 bits
         f60 = []               :: [iodata()] | undefined, % = 60, repeated
         social_facts           :: profile_pb:'Profile.ProfileSocialFacts'() | undefined, % = 61, optional
         f62                    :: 'FOLLOWSTATUS0' | 'SELF' | 'FOLLOWSTATUS2' | 'FOLLOWSTATUS3' | 'FOLLOWSTATUS4' | integer() | undefined, % = 62, optional, enum ProfileFollowStatus
         f63                    :: boolean() | 0 | 1 | undefined, % = 63, optional
         f64                    :: boolean() | 0 | 1 | undefined, % = 64, optional
         f65                    :: 'ENROLLEDPROGRAM0' | 'ENROLLEDPROGRAM1' | 'ENROLLEDPROGRAM2' | 'ENROLLEDPROGRAM3' | 'ENROLLEDPROGRAM4' | integer() | undefined, % = 65, optional, enum Profile.ProfileEnrolledProgram
         f66                    :: iodata() | undefined, % = 66, optional
         f67                    :: non_neg_integer() | undefined, % = 67, optional, 32 bits
         f68                    :: non_neg_integer() | undefined, % = 68, optional, 32 bits
         f69                    :: non_neg_integer() | undefined, % = 69, optional, 32 bits
         f70                    :: non_neg_integer() | undefined, % = 70, optional, 32 bits
         f71                    :: non_neg_integer() | undefined, % = 71, optional, 32 bits
         f72                    :: non_neg_integer() | undefined, % = 72, optional, 32 bits
         f73                    :: non_neg_integer() | undefined, % = 73, optional, 32 bits
         f74                    :: non_neg_integer() | undefined, % = 74, optional, 32 bits
         f75                    :: non_neg_integer() | undefined, % = 75, optional, 32 bits
         f76                    :: non_neg_integer() | undefined, % = 76, optional, 32 bits
         f77                    :: non_neg_integer() | undefined, % = 77, optional, 32 bits
         f78                    :: non_neg_integer() | undefined, % = 78, optional, 32 bits
         f79                    :: non_neg_integer() | undefined, % = 79, optional, 32 bits
         f80                    :: non_neg_integer() | undefined, % = 80, optional, 32 bits
         f81                    :: non_neg_integer() | undefined, % = 81, optional, 32 bits
         f82                    :: profile_pb:'Subscription'() | undefined, % = 82, optional
         mix_panel_distinct_id  :: unicode:chardata() | undefined, % = 83, optional
         f84                    :: non_neg_integer() | undefined, % = 84, optional, 32 bits
         f85                    :: non_neg_integer() | undefined, % = 85, optional, 32 bits
         sport                  :: 'SPORT0' | 'SPORT1' | 'SPORT2' | 'SPORT3' | 'SPORT4' | integer() | undefined, % = 86, optional, enum Profile.Sport
         f87                    :: non_neg_integer() | undefined, % = 87, optional, 32 bits
         f88                    :: boolean() | 0 | 1 | undefined, % = 88, optional
         preferred_language     :: unicode:chardata() | undefined, % = 89, optional
         f90                    :: non_neg_integer() | undefined, % = 90, optional, 32 bits
         f91                    :: non_neg_integer() | undefined, % = 91, optional, 32 bits
         f92                    :: non_neg_integer() | undefined, % = 92, optional, 32 bits
         f93                    :: non_neg_integer() | undefined, % = 93, optional, 32 bits
         f94                    :: non_neg_integer() | undefined, % = 94, optional, 32 bits
         f95                    :: non_neg_integer() | undefined, % = 95, optional, 32 bits
         f96                    :: non_neg_integer() | undefined, % = 96, optional, 32 bits
         f97                    :: non_neg_integer() | undefined, % = 97, optional, 32 bits
         f98                    :: non_neg_integer() | undefined, % = 98, optional, 32 bits
         f99                    :: non_neg_integer() | undefined, % = 99, optional, 32 bits
         f100                   :: non_neg_integer() | undefined, % = 100, optional, 32 bits
         f101                   :: non_neg_integer() | undefined, % = 101, optional, 32 bits
         f102                   :: non_neg_integer() | undefined, % = 102, optional, 32 bits
         f103                   :: non_neg_integer() | undefined, % = 103, optional, 32 bits
         f104                   :: non_neg_integer() | undefined, % = 104, optional, 32 bits
         f105                   :: boolean() | 0 | 1 | undefined, % = 105, optional
         f106                   :: boolean() | 0 | 1 | undefined, % = 106, optional
         f107 = []              :: [iodata()] | undefined, % = 107, repeated
         launched_game_client   :: unicode:chardata() | undefined, % = 108, optional
         f109                   :: integer() | undefined, % = 109, optional, 64 bits
         f110                   :: boolean() | 0 | 1 | undefined, % = 110, optional
         f114 = []              :: [profile_pb:'PacerSetting'()] | undefined, % = 114, repeated
         f117                   :: integer() | undefined, % = 117, optional, 32 bits
         f118                   :: integer() | undefined, % = 118, optional, 32 bits
         f119                   :: integer() | undefined, % = 119, optional, 32 bits
         f120                   :: integer() | undefined, % = 120, optional, 32 bits
         f121                   :: integer() | undefined, % = 121, optional, 32 bits
         f125                   :: integer() | undefined % = 125, optional, 32 bits
        }).
-endif.

-ifndef('PROFILES_PB_H').
-define('PROFILES_PB_H', true).
-record('Profiles',
        {profiles = []          :: [profile_pb:'Profile'()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('PROFILEENTITLEMENT_PB_H').
-define('PROFILEENTITLEMENT_PB_H', true).
-record('ProfileEntitlement',
        {f1                     :: 'ENTITLEMENTTYPE0' | 'ENTITLEMENTTYPE1' | 'ENTITLEMENTTYPE2' | 'ENTITLEMENTTYPE3' | 'ENTITLEMENTTYPE4' | integer() | undefined, % = 1, optional, enum ProfileEntitlement.EntitlementType
         f2                     :: integer() | undefined, % = 2, optional, 64 bits
         c                      :: 'ENTITLEMENTSTATUS0' | 'ENTITLEMENTSTATUS1' | 'ENTITLEMENTSTATUS2' | 'ENTITLEMENTSTATUS3' | 'ENTITLEMENTSTATUS4' | integer() | undefined, % = 3, optional, enum ProfileEntitlement.ProfileEntitlementStatus
         f4                     :: iodata() | undefined, % = 4, optional
         f5                     :: non_neg_integer() | undefined, % = 5, optional, 32 bits
         f6                     :: non_neg_integer() | undefined, % = 6, optional, 32 bits
         f7                     :: non_neg_integer() | undefined, % = 7, optional, 32 bits
         f8                     :: non_neg_integer() | undefined, % = 8, optional, 32 bits
         f9                     :: non_neg_integer() | undefined, % = 9, optional, 32 bits
         f10                    :: iodata() | undefined, % = 10, optional
         f11                    :: 'PLATFORM0' | 'PLATFORM1' | 'PLATFORM2' | 'PLATFORM3' | 'PLATFORM4' | 'PLATFORM5' | 'PLATFORM6' | integer() | undefined, % = 11, optional, enum ProfileEntitlement.Platform
         f12                    :: non_neg_integer() | undefined, % = 12, optional, 32 bits
         f13                    :: boolean() | 0 | 1 | undefined % = 13, optional
        }).
-endif.

-ifndef('SUBSCRIPTION_PB_H').
-define('SUBSCRIPTION_PB_H', true).
-record('Subscription',
        {f1                     :: 'GATEWAY0' | 'GATEWAY1' | 'GATEWAY2' | 'GATEWAY3' | 'GATEWAY4' | integer() | undefined, % = 1, optional, enum Subscription.Gateway
         f2                     :: 'STATUS0' | 'STATUS1' | 'ACTIVE' | 'ACTIVE_CANCELLED' | 'STATUS4' | 'STATUS5' | 'STATUS6' | integer() | undefined % = 2, optional, enum Subscription.SubscriptionStatus
        }).
-endif.

-ifndef('PACERSETTING_PB_H').
-define('PACERSETTING_PB_H', true).
-record('PacerSetting',
        {id                     :: integer() | undefined, % = 1, required, 64 bits
         number_value           :: integer() | undefined, % = 2, optional, 64 bits
         hex_value              :: non_neg_integer() | undefined, % = 3, optional, 32 bits
         string_value           :: unicode:chardata() | undefined % = 5, optional
        }).
-endif.

-endif.
