%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef('tcp-node-msgs_pb').
-define('tcp-node-msgs_pb', true).

-define('tcp-node-msgs_pb_gpb_version', "4.18.0").

-ifndef('SERVERDETAILS_PB_H').
-define('SERVERDETAILS_PB_H', true).
-record('ServerDetails',
        {f1                     :: integer() | undefined, % = 1, required, 32 bits
         f2                     :: integer() | undefined, % = 2, required, 32 bits
         ip                     :: unicode:chardata() | undefined, % = 3, required
         port                   :: integer() | undefined % = 4, required, 32 bits
        }).
-endif.

-ifndef('SERVERSTYPE1_PB_H').
-define('SERVERSTYPE1_PB_H', true).
-record('ServersType1',
        {details = []           :: ['tcp-node-msgs_pb':'ServerDetails'()] | undefined, % = 1, repeated
         f2                     :: integer() | undefined, % = 2, optional, 32 bits
         f3                     :: integer() | undefined, % = 3, optional, 32 bits
         f4                     :: integer() | undefined % = 4, optional, 32 bits
        }).
-endif.

-ifndef('SERVERCONNECTIONDETAILSWRAPPER_PB_H').
-define('SERVERCONNECTIONDETAILSWRAPPER_PB_H', true).
-record('ServerConnectionDetailsWrapper',
        {f1                     :: integer() | undefined, % = 1, required, 32 bits
         f2                     :: integer() | undefined, % = 2, required, 32 bits
         details = []           :: ['tcp-node-msgs_pb':'ServerDetails'()] | undefined % = 3, repeated
        }).
-endif.

-ifndef('SERVERSTYPE2_PB_H').
-define('SERVERSTYPE2_PB_H', true).
-record('ServersType2',
        {details_wrapper = []   :: ['tcp-node-msgs_pb':'ServerConnectionDetailsWrapper'()] | undefined, % = 1, repeated
         port                   :: integer() | undefined % = 2, required, 32 bits
        }).
-endif.

-ifndef('TCPSERVERINFO_PB_H').
-define('TCPSERVERINFO_PB_H', true).
-record('TCPServerInfo',
        {f1                     :: integer() | undefined, % = 1, optional, 32 bits
         player_id              :: integer() | undefined, % = 2, required, 32 bits
         f3                     :: integer() | undefined, % = 3, required, 32 bits
         servers = []           :: ['tcp-node-msgs_pb':'ServersType1'()] | undefined, % = 24, repeated
         other_servers = []     :: ['tcp-node-msgs_pb':'ServersType2'()] | undefined % = 25, repeated
        }).
-endif.

-ifndef('TCPHELLO_PB_H').
-define('TCPHELLO_PB_H', true).
-record('TCPHello',
        {player_id              :: integer() | undefined % = 2, required, 32 bits
        }).
-endif.

-ifndef('RECURRINGTCPRESPONSE_PB_H').
-define('RECURRINGTCPRESPONSE_PB_H', true).
-record('RecurringTCPResponse',
        {f1                     :: integer() | undefined, % = 1, optional, 32 bits
         player_id              :: integer() | undefined, % = 2, optional, 32 bits
         f3                     :: integer() | undefined, % = 3, optional, 32 bits
         f11                    :: integer() | undefined % = 11, optional, 32 bits
        }).
-endif.

-endif.
