%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef('udp-node-msgs_pb').
-define('udp-node-msgs_pb', true).

-define('udp-node-msgs_pb_gpb_version', "4.18.0").

-ifndef('PLAYERSTATE_PB_H').
-define('PLAYERSTATE_PB_H', true).
-record('PlayerState',
        {id                     :: integer() | undefined, % = 1, optional, 32 bits
         worldTime              :: integer() | undefined, % = 2, optional, 64 bits
         distance               :: integer() | undefined, % = 3, optional, 32 bits
         roadTime               :: integer() | undefined, % = 4, required, 32 bits
         laps                   :: integer() | undefined, % = 5, optional, 32 bits
         speed                  :: integer() | undefined, % = 6, optional, 32 bits
         roadPosition           :: integer() | undefined, % = 8, optional, 32 bits
         cadenceUHz             :: integer() | undefined, % = 9, optional, 32 bits
         heartrate              :: integer() | undefined, % = 11, optional, 32 bits
         power                  :: integer() | undefined, % = 12, optional, 32 bits
         heading                :: integer() | undefined, % = 13, optional, 64 bits
         lean                   :: integer() | undefined, % = 14, optional, 32 bits
         climbing               :: integer() | undefined, % = 15, optional, 32 bits
         time                   :: integer() | undefined, % = 16, optional, 32 bits
         f19                    :: integer() | undefined, % = 19, optional, 32 bits
         f20                    :: integer() | undefined, % = 20, optional, 32 bits
         progress               :: integer() | undefined, % = 21, optional, 32 bits
         customisationId        :: integer() | undefined, % = 22, optional, 64 bits
         justWatching           :: integer() | undefined, % = 23, optional, 32 bits
         calories               :: integer() | undefined, % = 24, optional, 32 bits
         x                      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 25, optional
         altitude               :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 26, optional
         y                      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 27, optional
         watchingRiderId        :: integer() | undefined, % = 28, optional, 32 bits
         groupId                :: integer() | undefined, % = 29, optional, 32 bits
         sport                  :: integer() | undefined, % = 31, optional, 64 bits
         f34                    :: float() | integer() | infinity | '-infinity' | nan | undefined % = 34, optional
        }).
-endif.

-ifndef('CLIENTTOSERVER_PB_H').
-define('CLIENTTOSERVER_PB_H', true).
-record('ClientToServer',
        {connected              :: integer() | undefined, % = 1, required, 32 bits
         player_id              :: integer() | undefined, % = 2, required, 32 bits
         world_time             :: integer() | undefined, % = 3, required, 64 bits
         seqno                  :: integer() | undefined, % = 4, required, 32 bits
         state                  :: 'udp-node-msgs_pb':'PlayerState'() | undefined, % = 7, required
         f8                     :: integer() | undefined, % = 8, required, 64 bits
         f9                     :: integer() | undefined, % = 9, required, 64 bits
         last_update            :: integer() | undefined, % = 10, required, 64 bits
         f11                    :: integer() | undefined, % = 11, required, 64 bits
         last_player_update     :: integer() | undefined % = 12, required, 64 bits
        }).
-endif.

-ifndef('SERVERTOCLIENT_PB_H').
-define('SERVERTOCLIENT_PB_H', true).
-record('ServerToClient',
        {f1                     :: integer() | undefined, % = 1, required, 32 bits
         player_id              :: integer() | undefined, % = 2, required, 32 bits
         world_time             :: integer() | undefined, % = 3, required, 64 bits
         seqno                  :: integer() | undefined, % = 4, optional, 32 bits
         f5                     :: integer() | undefined, % = 5, optional, 32 bits
         states = []            :: ['udp-node-msgs_pb':'PlayerState'()] | undefined, % = 8, repeated
         updates = []           :: ['udp-node-msgs_pb':'PlayerUpdate'()] | undefined, % = 9, repeated
         f11                    :: integer() | undefined, % = 11, optional, 64 bits
         num_msgs               :: integer() | undefined, % = 18, optional, 32 bits
         msgnum                 :: integer() | undefined % = 19, optional, 32 bits
        }).
-endif.

-ifndef('GHOST_PB_H').
-define('GHOST_PB_H', true).
-record('Ghost',
        {player_id              :: integer() | undefined, % = 1, required, 32 bits
         states = []            :: ['udp-node-msgs_pb':'PlayerState'()] | undefined % = 2, repeated
        }).
-endif.

-ifndef('GHOSTS_PB_H').
-define('GHOSTS_PB_H', true).
-record('Ghosts',
        {ghosts = []            :: ['udp-node-msgs_pb':'Ghost'()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('PLAYERUPDATE_PB_H').
-define('PLAYERUPDATE_PB_H', true).
-record('PlayerUpdate',
        {f1                     :: integer() | undefined, % = 1, optional, 64 bits
         f2                     :: integer() | undefined, % = 2, optional, 32 bits
         type                   :: integer() | undefined, % = 3, required, 32 bits
         payload                :: iodata() | undefined, % = 4, required
         world_time1            :: integer() | undefined, % = 5, optional, 64 bits
         x                      :: integer() | undefined, % = 6, optional, 64 bits
         altitude               :: integer() | undefined, % = 7, optional, 64 bits
         y                      :: integer() | undefined, % = 8, optional, 64 bits
         world_time2            :: integer() | undefined, % = 9, optional, 64 bits
         f11                    :: integer() | undefined, % = 11, optional, 64 bits
         f12                    :: integer() | undefined, % = 12, optional, 64 bits
         f14                    :: integer() | undefined, % = 14, optional, 64 bits
         f15                    :: integer() | undefined % = 15, optional, 64 bits
        }).
-endif.

-ifndef('CHATMESSAGE_PB_H').
-define('CHATMESSAGE_PB_H', true).
-record('ChatMessage',
        {rider_id               :: integer() | undefined, % = 1, required, 32 bits
         to_rider_id            :: integer() | undefined, % = 2, required, 32 bits
         f3                     :: integer() | undefined, % = 3, required, 32 bits
         firstName              :: unicode:chardata() | undefined, % = 4, required
         lastName               :: unicode:chardata() | undefined, % = 5, required
         message                :: unicode:chardata() | undefined, % = 6, required
         avatar                 :: unicode:chardata() | undefined, % = 7, optional
         countryCode            :: integer() | undefined, % = 8, required, 32 bits
         eventSubgroup          :: integer() | undefined % = 11, optional, 32 bits
        }).
-endif.

-ifndef('RIDEON_PB_H').
-define('RIDEON_PB_H', true).
-record('RideOn',
        {rider_id               :: integer() | undefined, % = 1, required, 32 bits
         to_rider_id            :: integer() | undefined, % = 2, required, 32 bits
         firstName              :: unicode:chardata() | undefined, % = 3, required
         lastName               :: unicode:chardata() | undefined, % = 4, required
         countryCode            :: integer() | undefined % = 5, required, 32 bits
        }).
-endif.

-ifndef('SEGMENTCOMPLETE_PB_H').
-define('SEGMENTCOMPLETE_PB_H', true).
-record('SegmentComplete',
        {f1                     :: integer() | undefined, % = 1, optional, 64 bits
         rider_id               :: integer() | undefined, % = 2, required, 32 bits
         f3                     :: integer() | undefined, % = 3, optional, 32 bits
         f4                     :: integer() | undefined, % = 4, optional, 64 bits
         segment_id             :: integer() | undefined, % = 5, optional, 64 bits
         f6                     :: integer() | undefined, % = 6, optional, 64 bits
         first_name             :: unicode:chardata() | undefined, % = 7, optional
         last_name              :: unicode:chardata() | undefined, % = 8, optional
         world_time             :: integer() | undefined, % = 9, optional, 64 bits
         milliseconds           :: integer() | undefined, % = 11, optional, 64 bits
         f12                    :: integer() | undefined, % = 12, optional, 32 bits
         weight_in_grams        :: integer() | undefined, % = 13, optional, 32 bits
         f14                    :: integer() | undefined, % = 14, optional, 32 bits
         avg_power              :: integer() | undefined, % = 15, optional, 32 bits
         f16                    :: integer() | undefined, % = 16, optional, 32 bits
         f7date                 :: unicode:chardata() | undefined, % = 17, optional
         f19                    :: integer() | undefined % = 19, optional, 32 bits
        }).
-endif.

-endif.
