%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(world_pb).
-define(world_pb, true).

-define(world_pb_gpb_version, "4.18.0").

-ifndef('WORLD_PB_H').
-define('WORLD_PB_H', true).
-record('World',
        {id                     :: non_neg_integer() | undefined, % = 1, required, 32 bits
         name                   :: unicode:chardata() | undefined, % = 2, required
         f3                     :: non_neg_integer() | undefined, % = 3, required, 32 bits
         f5                     :: non_neg_integer() | undefined, % = 5, required, 64 bits
         world_time             :: non_neg_integer() | undefined, % = 6, required, 64 bits
         real_time              :: non_neg_integer() | undefined, % = 7, required, 64 bits
         player_states = []     :: [world_pb:'Player'()] | undefined, % = 8, repeated
         pace_partner_states = [] :: [world_pb:'Player'()] | undefined % = 12, repeated
        }).
-endif.

-ifndef('WORLDS_PB_H').
-define('WORLDS_PB_H', true).
-record('Worlds',
        {worlds = []            :: [world_pb:'World'()] | undefined % = 1, repeated
        }).
-endif.

-ifndef('WORLDATTRIBUTES_PB_H').
-define('WORLDATTRIBUTES_PB_H', true).
-record('WorldAttributes',
        {world_time             :: integer() | undefined % = 2, required, 64 bits
        }).
-endif.

-ifndef('PLAYER_PB_H').
-define('PLAYER_PB_H', true).
-record('Player',
        {id                     :: non_neg_integer() | undefined, % = 1, required, 32 bits
         firstName              :: unicode:chardata() | undefined, % = 2, required
         lastName               :: unicode:chardata() | undefined, % = 3, required
         distance               :: non_neg_integer() | undefined, % = 4, optional, 32 bits
         time                   :: non_neg_integer() | undefined, % = 5, optional, 32 bits
         f6                     :: non_neg_integer() | undefined, % = 6, optional, 32 bits
         f8                     :: non_neg_integer() | undefined, % = 8, optional, 32 bits
         f9                     :: non_neg_integer() | undefined, % = 9, optional, 32 bits
         f10                    :: non_neg_integer() | undefined, % = 10, optional, 32 bits
         f11                    :: non_neg_integer() | undefined, % = 11, optional, 32 bits
         power                  :: non_neg_integer() | undefined, % = 12, optional, 32 bits
         f13                    :: non_neg_integer() | undefined, % = 13, optional, 32 bits
         x                      :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 14, optional
         altitude               :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 15, optional
         y                      :: float() | integer() | infinity | '-infinity' | nan | undefined % = 16, optional
        }).
-endif.

-endif.
