%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0

-ifndef(zfiles_pb).
-define(zfiles_pb, true).

-define(zfiles_pb_gpb_version, "4.18.0").

-ifndef('ZFILE_PB_H').
-define('ZFILE_PB_H', true).
-record('ZFile',
        {id                     :: non_neg_integer() | undefined, % = 1, required, 64 bits
         folder                 :: unicode:chardata() | undefined, % = 2, required
         filename               :: unicode:chardata() | undefined, % = 3, required
         timestamp              :: non_neg_integer() | undefined % = 4, required, 64 bits
        }).
-endif.

-endif.
