%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0
%% Version source: file
-module('login-response_pb').

-export([encode_msg/1, encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3, merge_msgs/4]).
-export([verify_msg/1, verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).

-include("login-response_pb.hrl").
-include("gpb.hrl").

%% enumerated types

-export_type([]).

%% message types
-type 'UDPNode'() :: #'UDPNode'{}.

-type 'UDPNodes'() :: #'UDPNodes'{}.

-type 'APIs'() :: #'APIs'{}.

-type 'ServerInfo'() :: #'ServerInfo'{}.

-type 'LoginResponse'() :: #'LoginResponse'{}.

-export_type(['UDPNode'/0, 'UDPNodes'/0, 'APIs'/0, 'ServerInfo'/0, 'LoginResponse'/0]).
-type '$msg_name'() :: 'UDPNode' | 'UDPNodes' | 'APIs' | 'ServerInfo' | 'LoginResponse'.
-type '$msg'() :: 'UDPNode'() | 'UDPNodes'() | 'APIs'() | 'ServerInfo'() | 'LoginResponse'().
-export_type(['$msg_name'/0, '$msg'/0]).

-dialyzer({no_underspecs, encode_msg/1}).
-spec encode_msg('$msg'()) -> binary().
encode_msg(Msg) when tuple_size(Msg) >= 1 -> encode_msg(Msg, element(1, Msg), []).

-dialyzer({no_underspecs, encode_msg/2}).
-spec encode_msg('$msg'(), '$msg_name'() | list()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []);
encode_msg(Msg, Opts) when tuple_size(Msg) >= 1, is_list(Opts) -> encode_msg(Msg, element(1, Msg), Opts).

-dialyzer({no_underspecs, encode_msg/3}).
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'UDPNode' -> encode_msg_UDPNode(id(Msg, TrUserData), TrUserData);
        'UDPNodes' -> encode_msg_UDPNodes(id(Msg, TrUserData), TrUserData);
        'APIs' -> encode_msg_APIs(id(Msg, TrUserData), TrUserData);
        'ServerInfo' -> encode_msg_ServerInfo(id(Msg, TrUserData), TrUserData);
        'LoginResponse' -> encode_msg_LoginResponse(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_UDPNode(Msg, TrUserData) -> encode_msg_UDPNode(Msg, <<>>, TrUserData).


encode_msg_UDPNode(#'UDPNode'{ip = F1, port = F2}, Bin, TrUserData) ->
    B1 = begin TrF1 = id(F1, TrUserData), e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData) end,
    begin TrF2 = id(F2, TrUserData), e_varint(TrF2, <<B1/binary, 16>>, TrUserData) end.

encode_msg_UDPNodes(Msg, TrUserData) -> encode_msg_UDPNodes(Msg, <<>>, TrUserData).


encode_msg_UDPNodes(#'UDPNodes'{node = F1}, Bin, TrUserData) ->
    begin
        TrF1 = id(F1, TrUserData),
        if TrF1 == [] -> Bin;
           true -> e_field_UDPNodes_node(TrF1, Bin, TrUserData)
        end
    end.

encode_msg_APIs(Msg, TrUserData) -> encode_msg_APIs(Msg, <<>>, TrUserData).


encode_msg_APIs(#'APIs'{todaysplan_url = F1, trainingpeaks_url = F2}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
            true -> begin TrF1 = id(F1, TrUserData), e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData) end
         end,
    if F2 == undefined -> B1;
       true -> begin TrF2 = id(F2, TrUserData), e_type_string(TrF2, <<B1/binary, 18>>, TrUserData) end
    end.

encode_msg_ServerInfo(Msg, TrUserData) -> encode_msg_ServerInfo(Msg, <<>>, TrUserData).


encode_msg_ServerInfo(#'ServerInfo'{relay_url = F1, apis = F2, time = F3, nodes = F4}, Bin, TrUserData) ->
    B1 = begin TrF1 = id(F1, TrUserData), e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData) end,
    B2 = begin TrF2 = id(F2, TrUserData), e_mfield_ServerInfo_apis(TrF2, <<B1/binary, 18>>, TrUserData) end,
    B3 = begin TrF3 = id(F3, TrUserData), e_varint(TrF3, <<B2/binary, 24>>, TrUserData) end,
    if F4 == undefined -> B3;
       true -> begin TrF4 = id(F4, TrUserData), e_mfield_ServerInfo_nodes(TrF4, <<B3/binary, 34>>, TrUserData) end
    end.

encode_msg_LoginResponse(Msg, TrUserData) -> encode_msg_LoginResponse(Msg, <<>>, TrUserData).


encode_msg_LoginResponse(#'LoginResponse'{session_state = F1, info = F2}, Bin, TrUserData) ->
    B1 = begin TrF1 = id(F1, TrUserData), e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData) end,
    begin TrF2 = id(F2, TrUserData), e_mfield_LoginResponse_info(TrF2, <<B1/binary, 18>>, TrUserData) end.

e_mfield_UDPNodes_node(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_UDPNode(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_UDPNodes_node([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_UDPNodes_node(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_UDPNodes_node(Rest, Bin3, TrUserData);
e_field_UDPNodes_node([], Bin, _TrUserData) -> Bin.

e_mfield_ServerInfo_apis(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_APIs(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_ServerInfo_nodes(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_UDPNodes(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_mfield_LoginResponse_info(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_ServerInfo(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit('UDPNode', Bin, TrUserData) -> id(decode_msg_UDPNode(Bin, TrUserData), TrUserData);
decode_msg_2_doit('UDPNodes', Bin, TrUserData) -> id(decode_msg_UDPNodes(Bin, TrUserData), TrUserData);
decode_msg_2_doit('APIs', Bin, TrUserData) -> id(decode_msg_APIs(Bin, TrUserData), TrUserData);
decode_msg_2_doit('ServerInfo', Bin, TrUserData) -> id(decode_msg_ServerInfo(Bin, TrUserData), TrUserData);
decode_msg_2_doit('LoginResponse', Bin, TrUserData) -> id(decode_msg_LoginResponse(Bin, TrUserData), TrUserData).



decode_msg_UDPNode(Bin, TrUserData) -> dfp_read_field_def_UDPNode(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), TrUserData).

dfp_read_field_def_UDPNode(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_UDPNode_ip(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_UDPNode(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_UDPNode_port(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_UDPNode(<<>>, 0, 0, _, F@_1, F@_2, _) -> #'UDPNode'{ip = F@_1, port = F@_2};
dfp_read_field_def_UDPNode(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_UDPNode(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_UDPNode(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_UDPNode(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_UDPNode(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_UDPNode_ip(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        16 -> d_field_UDPNode_port(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_UDPNode(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_UDPNode(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_UDPNode(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_UDPNode(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_UDPNode(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_UDPNode(<<>>, 0, 0, _, F@_1, F@_2, _) -> #'UDPNode'{ip = F@_1, port = F@_2}.

d_field_UDPNode_ip(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_UDPNode_ip(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_UDPNode_ip(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_UDPNode(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

d_field_UDPNode_port(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_UDPNode_port(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_UDPNode_port(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_UDPNode(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

skip_varint_UDPNode(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_UDPNode(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_UDPNode(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_UDPNode(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_UDPNode(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_UDPNode(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_UDPNode(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_UDPNode(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_UDPNode(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_UDPNode(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_UDPNode(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_UDPNode(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_UDPNode(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_UDPNode(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_UDPNodes(Bin, TrUserData) -> dfp_read_field_def_UDPNodes(Bin, 0, 0, 0, id([], TrUserData), TrUserData).

dfp_read_field_def_UDPNodes(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_UDPNodes_node(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_UDPNodes(<<>>, 0, 0, _, R1, TrUserData) -> #'UDPNodes'{node = lists_reverse(R1, TrUserData)};
dfp_read_field_def_UDPNodes(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_UDPNodes(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_UDPNodes(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_UDPNodes(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_UDPNodes(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_UDPNodes_node(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_UDPNodes(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_UDPNodes(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_UDPNodes(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_UDPNodes(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_UDPNodes(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_UDPNodes(<<>>, 0, 0, _, R1, TrUserData) -> #'UDPNodes'{node = lists_reverse(R1, TrUserData)}.

d_field_UDPNodes_node(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_UDPNodes_node(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_UDPNodes_node(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_UDPNode(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_UDPNodes(RestF, 0, 0, F, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_UDPNodes(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_UDPNodes(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_UDPNodes(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_UDPNodes(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_UDPNodes(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_UDPNodes(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_UDPNodes(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_UDPNodes(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_UDPNodes(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_UDPNodes(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_UDPNodes(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_UDPNodes(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_UDPNodes(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_UDPNodes(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_APIs(Bin, TrUserData) -> dfp_read_field_def_APIs(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), TrUserData).

dfp_read_field_def_APIs(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_APIs_todaysplan_url(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_APIs(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_APIs_trainingpeaks_url(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_APIs(<<>>, 0, 0, _, F@_1, F@_2, _) -> #'APIs'{todaysplan_url = F@_1, trainingpeaks_url = F@_2};
dfp_read_field_def_APIs(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_APIs(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_APIs(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_APIs(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_APIs(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_APIs_todaysplan_url(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        18 -> d_field_APIs_trainingpeaks_url(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_APIs(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_APIs(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_APIs(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_APIs(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_APIs(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_APIs(<<>>, 0, 0, _, F@_1, F@_2, _) -> #'APIs'{todaysplan_url = F@_1, trainingpeaks_url = F@_2}.

d_field_APIs_todaysplan_url(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_APIs_todaysplan_url(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_APIs_todaysplan_url(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_APIs(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

d_field_APIs_trainingpeaks_url(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_APIs_trainingpeaks_url(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_APIs_trainingpeaks_url(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_APIs(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

skip_varint_APIs(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_APIs(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_APIs(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_APIs(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_APIs(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_APIs(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_APIs(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_APIs(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_APIs(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_APIs(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_APIs(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_APIs(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_APIs(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_APIs(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_ServerInfo(Bin, TrUserData) -> dfp_read_field_def_ServerInfo(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), TrUserData).

dfp_read_field_def_ServerInfo(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServerInfo_relay_url(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServerInfo(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServerInfo_apis(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServerInfo(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServerInfo_time(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServerInfo(<<34, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServerInfo_nodes(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServerInfo(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #'ServerInfo'{relay_url = F@_1, apis = F@_2, time = F@_3, nodes = F@_4};
dfp_read_field_def_ServerInfo(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dg_read_field_def_ServerInfo(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

dg_read_field_def_ServerInfo(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 32 - 7 -> dg_read_field_def_ServerInfo(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dg_read_field_def_ServerInfo(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_ServerInfo_relay_url(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        18 -> d_field_ServerInfo_apis(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        24 -> d_field_ServerInfo_time(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        34 -> d_field_ServerInfo_nodes(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_ServerInfo(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                1 -> skip_64_ServerInfo(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                2 -> skip_length_delimited_ServerInfo(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                3 -> skip_group_ServerInfo(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                5 -> skip_32_ServerInfo(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData)
            end
    end;
dg_read_field_def_ServerInfo(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #'ServerInfo'{relay_url = F@_1, apis = F@_2, time = F@_3, nodes = F@_4}.

d_field_ServerInfo_relay_url(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServerInfo_relay_url(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServerInfo_relay_url(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_ServerInfo(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, TrUserData).

d_field_ServerInfo_apis(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServerInfo_apis(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServerInfo_apis(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, Prev, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_APIs(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_ServerInfo(RestF,
                                  0,
                                  0,
                                  F,
                                  F@_1,
                                  if Prev == undefined -> NewFValue;
                                     true -> merge_msg_APIs(Prev, NewFValue, TrUserData)
                                  end,
                                  F@_3,
                                  F@_4,
                                  TrUserData).

d_field_ServerInfo_time(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServerInfo_time(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServerInfo_time(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 18446744073709551615, TrUserData), Rest},
    dfp_read_field_def_ServerInfo(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, TrUserData).

d_field_ServerInfo_nodes(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServerInfo_nodes(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServerInfo_nodes(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_UDPNodes(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_ServerInfo(RestF,
                                  0,
                                  0,
                                  F,
                                  F@_1,
                                  F@_2,
                                  F@_3,
                                  if Prev == undefined -> NewFValue;
                                     true -> merge_msg_UDPNodes(Prev, NewFValue, TrUserData)
                                  end,
                                  TrUserData).

skip_varint_ServerInfo(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> skip_varint_ServerInfo(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_varint_ServerInfo(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_ServerInfo(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_length_delimited_ServerInfo(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> skip_length_delimited_ServerInfo(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_length_delimited_ServerInfo(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_ServerInfo(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_group_ServerInfo(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_ServerInfo(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_32_ServerInfo(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_ServerInfo(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_64_ServerInfo(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_ServerInfo(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

decode_msg_LoginResponse(Bin, TrUserData) -> dfp_read_field_def_LoginResponse(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), TrUserData).

dfp_read_field_def_LoginResponse(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_LoginResponse_session_state(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_LoginResponse(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_LoginResponse_info(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_LoginResponse(<<>>, 0, 0, _, F@_1, F@_2, _) -> #'LoginResponse'{session_state = F@_1, info = F@_2};
dfp_read_field_def_LoginResponse(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_LoginResponse(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_LoginResponse(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_LoginResponse(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_LoginResponse(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_LoginResponse_session_state(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        18 -> d_field_LoginResponse_info(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_LoginResponse(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_LoginResponse(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_LoginResponse(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_LoginResponse(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_LoginResponse(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_LoginResponse(<<>>, 0, 0, _, F@_1, F@_2, _) -> #'LoginResponse'{session_state = F@_1, info = F@_2}.

d_field_LoginResponse_session_state(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_LoginResponse_session_state(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_LoginResponse_session_state(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_LoginResponse(RestF, 0, 0, F, NewFValue, F@_2, TrUserData).

d_field_LoginResponse_info(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_LoginResponse_info(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_LoginResponse_info(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_ServerInfo(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_LoginResponse(RestF,
                                     0,
                                     0,
                                     F,
                                     F@_1,
                                     if Prev == undefined -> NewFValue;
                                        true -> merge_msg_ServerInfo(Prev, NewFValue, TrUserData)
                                     end,
                                     TrUserData).

skip_varint_LoginResponse(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_LoginResponse(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_LoginResponse(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_LoginResponse(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_LoginResponse(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_LoginResponse(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_LoginResponse(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_LoginResponse(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_LoginResponse(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_LoginResponse(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_LoginResponse(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_LoginResponse(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_LoginResponse(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_LoginResponse(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) when element(1, Prev) =:= element(1, New) -> merge_msgs(Prev, New, element(1, Prev), []).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []);
merge_msgs(Prev, New, Opts) when element(1, Prev) =:= element(1, New), is_list(Opts) -> merge_msgs(Prev, New, element(1, Prev), Opts).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'UDPNode' -> merge_msg_UDPNode(Prev, New, TrUserData);
        'UDPNodes' -> merge_msg_UDPNodes(Prev, New, TrUserData);
        'APIs' -> merge_msg_APIs(Prev, New, TrUserData);
        'ServerInfo' -> merge_msg_ServerInfo(Prev, New, TrUserData);
        'LoginResponse' -> merge_msg_LoginResponse(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_UDPNode/3}).
merge_msg_UDPNode(#'UDPNode'{}, #'UDPNode'{ip = NFip, port = NFport}, _) -> #'UDPNode'{ip = NFip, port = NFport}.

-compile({nowarn_unused_function,merge_msg_UDPNodes/3}).
merge_msg_UDPNodes(#'UDPNodes'{node = PFnode}, #'UDPNodes'{node = NFnode}, TrUserData) ->
    #'UDPNodes'{node =
                    if PFnode /= undefined, NFnode /= undefined -> 'erlang_++'(PFnode, NFnode, TrUserData);
                       PFnode == undefined -> NFnode;
                       NFnode == undefined -> PFnode
                    end}.

-compile({nowarn_unused_function,merge_msg_APIs/3}).
merge_msg_APIs(#'APIs'{todaysplan_url = PFtodaysplan_url, trainingpeaks_url = PFtrainingpeaks_url}, #'APIs'{todaysplan_url = NFtodaysplan_url, trainingpeaks_url = NFtrainingpeaks_url}, _) ->
    #'APIs'{todaysplan_url =
                if NFtodaysplan_url =:= undefined -> PFtodaysplan_url;
                   true -> NFtodaysplan_url
                end,
            trainingpeaks_url =
                if NFtrainingpeaks_url =:= undefined -> PFtrainingpeaks_url;
                   true -> NFtrainingpeaks_url
                end}.

-compile({nowarn_unused_function,merge_msg_ServerInfo/3}).
merge_msg_ServerInfo(#'ServerInfo'{apis = PFapis, nodes = PFnodes}, #'ServerInfo'{relay_url = NFrelay_url, apis = NFapis, time = NFtime, nodes = NFnodes}, TrUserData) ->
    #'ServerInfo'{relay_url = NFrelay_url, apis = merge_msg_APIs(PFapis, NFapis, TrUserData), time = NFtime,
                  nodes =
                      if PFnodes /= undefined, NFnodes /= undefined -> merge_msg_UDPNodes(PFnodes, NFnodes, TrUserData);
                         PFnodes == undefined -> NFnodes;
                         NFnodes == undefined -> PFnodes
                      end}.

-compile({nowarn_unused_function,merge_msg_LoginResponse/3}).
merge_msg_LoginResponse(#'LoginResponse'{info = PFinfo}, #'LoginResponse'{session_state = NFsession_state, info = NFinfo}, TrUserData) -> #'LoginResponse'{session_state = NFsession_state, info = merge_msg_ServerInfo(PFinfo, NFinfo, TrUserData)}.


verify_msg(Msg) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), []);
verify_msg(X) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []);
verify_msg(Msg, Opts) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), Opts);
verify_msg(X, _Opts) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'UDPNode' -> v_msg_UDPNode(Msg, [MsgName], TrUserData);
        'UDPNodes' -> v_msg_UDPNodes(Msg, [MsgName], TrUserData);
        'APIs' -> v_msg_APIs(Msg, [MsgName], TrUserData);
        'ServerInfo' -> v_msg_ServerInfo(Msg, [MsgName], TrUserData);
        'LoginResponse' -> v_msg_LoginResponse(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_UDPNode/3}).
-dialyzer({nowarn_function,v_msg_UDPNode/3}).
v_msg_UDPNode(#'UDPNode'{ip = F1, port = F2}, Path, TrUserData) ->
    v_type_string(F1, [ip | Path], TrUserData),
    v_type_uint32(F2, [port | Path], TrUserData),
    ok;
v_msg_UDPNode(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'UDPNode'}, X, Path).

-compile({nowarn_unused_function,v_msg_UDPNodes/3}).
-dialyzer({nowarn_function,v_msg_UDPNodes/3}).
v_msg_UDPNodes(#'UDPNodes'{node = F1}, Path, TrUserData) ->
    if is_list(F1) ->
           _ = [v_msg_UDPNode(Elem, [node | Path], TrUserData) || Elem <- F1],
           ok;
       true -> mk_type_error({invalid_list_of, {msg, 'UDPNode'}}, F1, [node | Path])
    end,
    ok;
v_msg_UDPNodes(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'UDPNodes'}, X, Path).

-compile({nowarn_unused_function,v_msg_APIs/3}).
-dialyzer({nowarn_function,v_msg_APIs/3}).
v_msg_APIs(#'APIs'{todaysplan_url = F1, trainingpeaks_url = F2}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_string(F1, [todaysplan_url | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_string(F2, [trainingpeaks_url | Path], TrUserData)
    end,
    ok;
v_msg_APIs(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'APIs'}, X, Path).

-compile({nowarn_unused_function,v_msg_ServerInfo/3}).
-dialyzer({nowarn_function,v_msg_ServerInfo/3}).
v_msg_ServerInfo(#'ServerInfo'{relay_url = F1, apis = F2, time = F3, nodes = F4}, Path, TrUserData) ->
    v_type_string(F1, [relay_url | Path], TrUserData),
    v_msg_APIs(F2, [apis | Path], TrUserData),
    v_type_uint64(F3, [time | Path], TrUserData),
    if F4 == undefined -> ok;
       true -> v_msg_UDPNodes(F4, [nodes | Path], TrUserData)
    end,
    ok;
v_msg_ServerInfo(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'ServerInfo'}, X, Path).

-compile({nowarn_unused_function,v_msg_LoginResponse/3}).
-dialyzer({nowarn_function,v_msg_LoginResponse/3}).
v_msg_LoginResponse(#'LoginResponse'{session_state = F1, info = F2}, Path, TrUserData) ->
    v_type_string(F1, [session_state | Path], TrUserData),
    v_msg_ServerInfo(F2, [info | Path], TrUserData),
    ok;
v_msg_LoginResponse(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'LoginResponse'}, X, Path).

-compile({nowarn_unused_function,v_type_uint32/3}).
-dialyzer({nowarn_function,v_type_uint32/3}).
v_type_uint32(N, _Path, _TrUserData) when 0 =< N, N =< 4294967295 -> ok;
v_type_uint32(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, uint32, unsigned, 32}, N, Path);
v_type_uint32(X, Path, _TrUserData) -> mk_type_error({bad_integer, uint32, unsigned, 32}, X, Path).

-compile({nowarn_unused_function,v_type_uint64/3}).
-dialyzer({nowarn_function,v_type_uint64/3}).
v_type_uint64(N, _Path, _TrUserData) when 0 =< N, N =< 18446744073709551615 -> ok;
v_type_uint64(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, uint64, unsigned, 64}, N, Path);
v_type_uint64(X, Path, _TrUserData) -> mk_type_error({bad_integer, uint64, unsigned, 64}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{msg, 'UDPNode'}, [#field{name = ip, fnum = 1, rnum = 2, type = string, occurrence = required, opts = []}, #field{name = port, fnum = 2, rnum = 3, type = uint32, occurrence = required, opts = []}]},
     {{msg, 'UDPNodes'}, [#field{name = node, fnum = 1, rnum = 2, type = {msg, 'UDPNode'}, occurrence = repeated, opts = []}]},
     {{msg, 'APIs'}, [#field{name = todaysplan_url, fnum = 1, rnum = 2, type = string, occurrence = optional, opts = []}, #field{name = trainingpeaks_url, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []}]},
     {{msg, 'ServerInfo'},
      [#field{name = relay_url, fnum = 1, rnum = 2, type = string, occurrence = required, opts = []},
       #field{name = apis, fnum = 2, rnum = 3, type = {msg, 'APIs'}, occurrence = required, opts = []},
       #field{name = time, fnum = 3, rnum = 4, type = uint64, occurrence = required, opts = []},
       #field{name = nodes, fnum = 4, rnum = 5, type = {msg, 'UDPNodes'}, occurrence = optional, opts = []}]},
     {{msg, 'LoginResponse'}, [#field{name = session_state, fnum = 1, rnum = 2, type = string, occurrence = required, opts = []}, #field{name = info, fnum = 2, rnum = 3, type = {msg, 'ServerInfo'}, occurrence = required, opts = []}]}].


get_msg_names() -> ['UDPNode', 'UDPNodes', 'APIs', 'ServerInfo', 'LoginResponse'].


get_group_names() -> [].


get_msg_or_group_names() -> ['UDPNode', 'UDPNodes', 'APIs', 'ServerInfo', 'LoginResponse'].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) -> erlang:error({no_such_enum, EnumName}).


find_msg_def('UDPNode') -> [#field{name = ip, fnum = 1, rnum = 2, type = string, occurrence = required, opts = []}, #field{name = port, fnum = 2, rnum = 3, type = uint32, occurrence = required, opts = []}];
find_msg_def('UDPNodes') -> [#field{name = node, fnum = 1, rnum = 2, type = {msg, 'UDPNode'}, occurrence = repeated, opts = []}];
find_msg_def('APIs') -> [#field{name = todaysplan_url, fnum = 1, rnum = 2, type = string, occurrence = optional, opts = []}, #field{name = trainingpeaks_url, fnum = 2, rnum = 3, type = string, occurrence = optional, opts = []}];
find_msg_def('ServerInfo') ->
    [#field{name = relay_url, fnum = 1, rnum = 2, type = string, occurrence = required, opts = []},
     #field{name = apis, fnum = 2, rnum = 3, type = {msg, 'APIs'}, occurrence = required, opts = []},
     #field{name = time, fnum = 3, rnum = 4, type = uint64, occurrence = required, opts = []},
     #field{name = nodes, fnum = 4, rnum = 5, type = {msg, 'UDPNodes'}, occurrence = optional, opts = []}];
find_msg_def('LoginResponse') -> [#field{name = session_state, fnum = 1, rnum = 2, type = string, occurrence = required, opts = []}, #field{name = info, fnum = 2, rnum = 3, type = {msg, 'ServerInfo'}, occurrence = required, opts = []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) -> erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) -> erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) -> erlang:error({no_such_rpc, ServiceName, RpcName}).


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"zwiftj.api.model.UDPNode">>) -> 'UDPNode';
fqbin_to_msg_name(<<"zwiftj.api.model.UDPNodes">>) -> 'UDPNodes';
fqbin_to_msg_name(<<"zwiftj.api.model.APIs">>) -> 'APIs';
fqbin_to_msg_name(<<"zwiftj.api.model.ServerInfo">>) -> 'ServerInfo';
fqbin_to_msg_name(<<"zwiftj.api.model.LoginResponse">>) -> 'LoginResponse';
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin('UDPNode') -> <<"zwiftj.api.model.UDPNode">>;
msg_name_to_fqbin('UDPNodes') -> <<"zwiftj.api.model.UDPNodes">>;
msg_name_to_fqbin('APIs') -> <<"zwiftj.api.model.APIs">>;
msg_name_to_fqbin('ServerInfo') -> <<"zwiftj.api.model.ServerInfo">>;
msg_name_to_fqbin('LoginResponse') -> <<"zwiftj.api.model.LoginResponse">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec fqbin_to_enum_name(_) -> no_return().
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


-spec enum_name_to_fqbin(_) -> no_return().
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> 'zwiftj.api.model'.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> false.


source_basename() -> "login-response.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["login-response.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["login-response"].


get_msg_containment("login-response") -> ['APIs', 'LoginResponse', 'ServerInfo', 'UDPNode', 'UDPNodes'];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("login-response") -> undefined;
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("login-response") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("login-response") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("login-response") -> [];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.UDPNodes">>) -> "login-response";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.APIs">>) -> "login-response";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.UDPNode">>) -> "login-response";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.LoginResponse">>) -> "login-response";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.ServerInfo">>) -> "login-response";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec get_proto_by_service_name_as_fqbin(_) -> no_return().
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


-spec get_proto_by_enum_name_as_fqbin(_) -> no_return().
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


-spec get_protos_by_pkg_name_as_fqbin(_) -> no_return().
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.18.0".

gpb_version_as_list() ->
    [4,18,0].

gpb_version_source() ->
    "file".
