%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0
%% Version source: file
-module('tcp-node-msgs_pb').

-export([encode_msg/1, encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3, merge_msgs/4]).
-export([verify_msg/1, verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).

-include("tcp-node-msgs_pb.hrl").
-include("gpb.hrl").

%% enumerated types

-export_type([]).

%% message types
-type 'ServerDetails'() :: #'ServerDetails'{}.

-type 'ServersType1'() :: #'ServersType1'{}.

-type 'ServerConnectionDetailsWrapper'() :: #'ServerConnectionDetailsWrapper'{}.

-type 'ServersType2'() :: #'ServersType2'{}.

-type 'TCPServerInfo'() :: #'TCPServerInfo'{}.

-type 'TCPHello'() :: #'TCPHello'{}.

-type 'RecurringTCPResponse'() :: #'RecurringTCPResponse'{}.

-export_type(['ServerDetails'/0, 'ServersType1'/0, 'ServerConnectionDetailsWrapper'/0, 'ServersType2'/0, 'TCPServerInfo'/0, 'TCPHello'/0, 'RecurringTCPResponse'/0]).
-type '$msg_name'() :: 'ServerDetails' | 'ServersType1' | 'ServerConnectionDetailsWrapper' | 'ServersType2' | 'TCPServerInfo' | 'TCPHello' | 'RecurringTCPResponse'.
-type '$msg'() :: 'ServerDetails'() | 'ServersType1'() | 'ServerConnectionDetailsWrapper'() | 'ServersType2'() | 'TCPServerInfo'() | 'TCPHello'() | 'RecurringTCPResponse'().
-export_type(['$msg_name'/0, '$msg'/0]).

-dialyzer({no_underspecs, encode_msg/1}).
-spec encode_msg('$msg'()) -> binary().
encode_msg(Msg) when tuple_size(Msg) >= 1 -> encode_msg(Msg, element(1, Msg), []).

-dialyzer({no_underspecs, encode_msg/2}).
-spec encode_msg('$msg'(), '$msg_name'() | list()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []);
encode_msg(Msg, Opts) when tuple_size(Msg) >= 1, is_list(Opts) -> encode_msg(Msg, element(1, Msg), Opts).

-dialyzer({no_underspecs, encode_msg/3}).
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'ServerDetails' -> encode_msg_ServerDetails(id(Msg, TrUserData), TrUserData);
        'ServersType1' -> encode_msg_ServersType1(id(Msg, TrUserData), TrUserData);
        'ServerConnectionDetailsWrapper' -> encode_msg_ServerConnectionDetailsWrapper(id(Msg, TrUserData), TrUserData);
        'ServersType2' -> encode_msg_ServersType2(id(Msg, TrUserData), TrUserData);
        'TCPServerInfo' -> encode_msg_TCPServerInfo(id(Msg, TrUserData), TrUserData);
        'TCPHello' -> encode_msg_TCPHello(id(Msg, TrUserData), TrUserData);
        'RecurringTCPResponse' -> encode_msg_RecurringTCPResponse(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_ServerDetails(Msg, TrUserData) -> encode_msg_ServerDetails(Msg, <<>>, TrUserData).


encode_msg_ServerDetails(#'ServerDetails'{f1 = F1, f2 = F2, ip = F3, port = F4}, Bin, TrUserData) ->
    B1 = begin TrF1 = id(F1, TrUserData), e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData) end,
    B2 = begin TrF2 = id(F2, TrUserData), e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData) end,
    B3 = begin TrF3 = id(F3, TrUserData), e_type_string(TrF3, <<B2/binary, 26>>, TrUserData) end,
    begin TrF4 = id(F4, TrUserData), e_type_int32(TrF4, <<B3/binary, 32>>, TrUserData) end.

encode_msg_ServersType1(Msg, TrUserData) -> encode_msg_ServersType1(Msg, <<>>, TrUserData).


encode_msg_ServersType1(#'ServersType1'{details = F1, f2 = F2, f3 = F3, f4 = F4}, Bin, TrUserData) ->
    B1 = begin
             TrF1 = id(F1, TrUserData),
             if TrF1 == [] -> Bin;
                true -> e_field_ServersType1_details(TrF1, Bin, TrUserData)
             end
         end,
    B2 = if F2 == undefined -> B1;
            true -> begin TrF2 = id(F2, TrUserData), e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData) end
         end,
    B3 = if F3 == undefined -> B2;
            true -> begin TrF3 = id(F3, TrUserData), e_type_int32(TrF3, <<B2/binary, 24>>, TrUserData) end
         end,
    if F4 == undefined -> B3;
       true -> begin TrF4 = id(F4, TrUserData), e_type_int32(TrF4, <<B3/binary, 32>>, TrUserData) end
    end.

encode_msg_ServerConnectionDetailsWrapper(Msg, TrUserData) -> encode_msg_ServerConnectionDetailsWrapper(Msg, <<>>, TrUserData).


encode_msg_ServerConnectionDetailsWrapper(#'ServerConnectionDetailsWrapper'{f1 = F1, f2 = F2, details = F3}, Bin, TrUserData) ->
    B1 = begin TrF1 = id(F1, TrUserData), e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData) end,
    B2 = begin TrF2 = id(F2, TrUserData), e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData) end,
    begin
        TrF3 = id(F3, TrUserData),
        if TrF3 == [] -> B2;
           true -> e_field_ServerConnectionDetailsWrapper_details(TrF3, B2, TrUserData)
        end
    end.

encode_msg_ServersType2(Msg, TrUserData) -> encode_msg_ServersType2(Msg, <<>>, TrUserData).


encode_msg_ServersType2(#'ServersType2'{details_wrapper = F1, port = F2}, Bin, TrUserData) ->
    B1 = begin
             TrF1 = id(F1, TrUserData),
             if TrF1 == [] -> Bin;
                true -> e_field_ServersType2_details_wrapper(TrF1, Bin, TrUserData)
             end
         end,
    begin TrF2 = id(F2, TrUserData), e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData) end.

encode_msg_TCPServerInfo(Msg, TrUserData) -> encode_msg_TCPServerInfo(Msg, <<>>, TrUserData).


encode_msg_TCPServerInfo(#'TCPServerInfo'{f1 = F1, player_id = F2, f3 = F3, servers = F4, other_servers = F5}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
            true -> begin TrF1 = id(F1, TrUserData), e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData) end
         end,
    B2 = begin TrF2 = id(F2, TrUserData), e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData) end,
    B3 = begin TrF3 = id(F3, TrUserData), e_type_int32(TrF3, <<B2/binary, 24>>, TrUserData) end,
    B4 = begin
             TrF4 = id(F4, TrUserData),
             if TrF4 == [] -> B3;
                true -> e_field_TCPServerInfo_servers(TrF4, B3, TrUserData)
             end
         end,
    begin
        TrF5 = id(F5, TrUserData),
        if TrF5 == [] -> B4;
           true -> e_field_TCPServerInfo_other_servers(TrF5, B4, TrUserData)
        end
    end.

encode_msg_TCPHello(Msg, TrUserData) -> encode_msg_TCPHello(Msg, <<>>, TrUserData).


encode_msg_TCPHello(#'TCPHello'{player_id = F1}, Bin, TrUserData) -> begin TrF1 = id(F1, TrUserData), e_type_int32(TrF1, <<Bin/binary, 16>>, TrUserData) end.

encode_msg_RecurringTCPResponse(Msg, TrUserData) -> encode_msg_RecurringTCPResponse(Msg, <<>>, TrUserData).


encode_msg_RecurringTCPResponse(#'RecurringTCPResponse'{f1 = F1, player_id = F2, f3 = F3, f11 = F4}, Bin, TrUserData) ->
    B1 = if F1 == undefined -> Bin;
            true -> begin TrF1 = id(F1, TrUserData), e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData) end
         end,
    B2 = if F2 == undefined -> B1;
            true -> begin TrF2 = id(F2, TrUserData), e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData) end
         end,
    B3 = if F3 == undefined -> B2;
            true -> begin TrF3 = id(F3, TrUserData), e_type_int32(TrF3, <<B2/binary, 24>>, TrUserData) end
         end,
    if F4 == undefined -> B3;
       true -> begin TrF4 = id(F4, TrUserData), e_type_int32(TrF4, <<B3/binary, 88>>, TrUserData) end
    end.

e_mfield_ServersType1_details(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_ServerDetails(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_ServersType1_details([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_ServersType1_details(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_ServersType1_details(Rest, Bin3, TrUserData);
e_field_ServersType1_details([], Bin, _TrUserData) -> Bin.

e_mfield_ServerConnectionDetailsWrapper_details(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_ServerDetails(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_ServerConnectionDetailsWrapper_details([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 26>>,
    Bin3 = e_mfield_ServerConnectionDetailsWrapper_details(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_ServerConnectionDetailsWrapper_details(Rest, Bin3, TrUserData);
e_field_ServerConnectionDetailsWrapper_details([], Bin, _TrUserData) -> Bin.

e_mfield_ServersType2_details_wrapper(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_ServerConnectionDetailsWrapper(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_ServersType2_details_wrapper([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_ServersType2_details_wrapper(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_ServersType2_details_wrapper(Rest, Bin3, TrUserData);
e_field_ServersType2_details_wrapper([], Bin, _TrUserData) -> Bin.

e_mfield_TCPServerInfo_servers(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_ServersType1(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_TCPServerInfo_servers([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 194, 1>>,
    Bin3 = e_mfield_TCPServerInfo_servers(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_TCPServerInfo_servers(Rest, Bin3, TrUserData);
e_field_TCPServerInfo_servers([], Bin, _TrUserData) -> Bin.

e_mfield_TCPServerInfo_other_servers(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_ServersType2(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_TCPServerInfo_other_servers([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 202, 1>>,
    Bin3 = e_mfield_TCPServerInfo_other_servers(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_TCPServerInfo_other_servers(Rest, Bin3, TrUserData);
e_field_TCPServerInfo_other_servers([], Bin, _TrUserData) -> Bin.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit('ServerDetails', Bin, TrUserData) -> id(decode_msg_ServerDetails(Bin, TrUserData), TrUserData);
decode_msg_2_doit('ServersType1', Bin, TrUserData) -> id(decode_msg_ServersType1(Bin, TrUserData), TrUserData);
decode_msg_2_doit('ServerConnectionDetailsWrapper', Bin, TrUserData) -> id(decode_msg_ServerConnectionDetailsWrapper(Bin, TrUserData), TrUserData);
decode_msg_2_doit('ServersType2', Bin, TrUserData) -> id(decode_msg_ServersType2(Bin, TrUserData), TrUserData);
decode_msg_2_doit('TCPServerInfo', Bin, TrUserData) -> id(decode_msg_TCPServerInfo(Bin, TrUserData), TrUserData);
decode_msg_2_doit('TCPHello', Bin, TrUserData) -> id(decode_msg_TCPHello(Bin, TrUserData), TrUserData);
decode_msg_2_doit('RecurringTCPResponse', Bin, TrUserData) -> id(decode_msg_RecurringTCPResponse(Bin, TrUserData), TrUserData).



decode_msg_ServerDetails(Bin, TrUserData) -> dfp_read_field_def_ServerDetails(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), TrUserData).

dfp_read_field_def_ServerDetails(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServerDetails_f1(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServerDetails(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServerDetails_f2(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServerDetails(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServerDetails_ip(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServerDetails(<<32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServerDetails_port(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServerDetails(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #'ServerDetails'{f1 = F@_1, f2 = F@_2, ip = F@_3, port = F@_4};
dfp_read_field_def_ServerDetails(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dg_read_field_def_ServerDetails(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

dg_read_field_def_ServerDetails(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 32 - 7 -> dg_read_field_def_ServerDetails(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dg_read_field_def_ServerDetails(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> d_field_ServerDetails_f1(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        16 -> d_field_ServerDetails_f2(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        26 -> d_field_ServerDetails_ip(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        32 -> d_field_ServerDetails_port(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_ServerDetails(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                1 -> skip_64_ServerDetails(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                2 -> skip_length_delimited_ServerDetails(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                3 -> skip_group_ServerDetails(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                5 -> skip_32_ServerDetails(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData)
            end
    end;
dg_read_field_def_ServerDetails(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #'ServerDetails'{f1 = F@_1, f2 = F@_2, ip = F@_3, port = F@_4}.

d_field_ServerDetails_f1(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServerDetails_f1(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServerDetails_f1(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_ServerDetails(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, TrUserData).

d_field_ServerDetails_f2(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServerDetails_f2(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServerDetails_f2(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_ServerDetails(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, TrUserData).

d_field_ServerDetails_ip(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServerDetails_ip(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServerDetails_ip(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_ServerDetails(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, TrUserData).

d_field_ServerDetails_port(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServerDetails_port(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServerDetails_port(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_ServerDetails(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, TrUserData).

skip_varint_ServerDetails(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> skip_varint_ServerDetails(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_varint_ServerDetails(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_ServerDetails(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_length_delimited_ServerDetails(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> skip_length_delimited_ServerDetails(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_length_delimited_ServerDetails(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_ServerDetails(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_group_ServerDetails(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_ServerDetails(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_32_ServerDetails(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_ServerDetails(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_64_ServerDetails(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_ServerDetails(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

decode_msg_ServersType1(Bin, TrUserData) -> dfp_read_field_def_ServersType1(Bin, 0, 0, 0, id([], TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), TrUserData).

dfp_read_field_def_ServersType1(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServersType1_details(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServersType1(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServersType1_f2(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServersType1(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServersType1_f3(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServersType1(<<32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_ServersType1_f4(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_ServersType1(<<>>, 0, 0, _, R1, F@_2, F@_3, F@_4, TrUserData) -> #'ServersType1'{details = lists_reverse(R1, TrUserData), f2 = F@_2, f3 = F@_3, f4 = F@_4};
dfp_read_field_def_ServersType1(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dg_read_field_def_ServersType1(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

dg_read_field_def_ServersType1(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 32 - 7 -> dg_read_field_def_ServersType1(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dg_read_field_def_ServersType1(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_ServersType1_details(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        16 -> d_field_ServersType1_f2(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        24 -> d_field_ServersType1_f3(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        32 -> d_field_ServersType1_f4(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_ServersType1(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                1 -> skip_64_ServersType1(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                2 -> skip_length_delimited_ServersType1(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                3 -> skip_group_ServersType1(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                5 -> skip_32_ServersType1(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData)
            end
    end;
dg_read_field_def_ServersType1(<<>>, 0, 0, _, R1, F@_2, F@_3, F@_4, TrUserData) -> #'ServersType1'{details = lists_reverse(R1, TrUserData), f2 = F@_2, f3 = F@_3, f4 = F@_4}.

d_field_ServersType1_details(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServersType1_details(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServersType1_details(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_ServerDetails(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_ServersType1(RestF, 0, 0, F, cons(NewFValue, Prev, TrUserData), F@_2, F@_3, F@_4, TrUserData).

d_field_ServersType1_f2(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServersType1_f2(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServersType1_f2(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_ServersType1(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, TrUserData).

d_field_ServersType1_f3(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServersType1_f3(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServersType1_f3(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_ServersType1(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, TrUserData).

d_field_ServersType1_f4(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_ServersType1_f4(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_ServersType1_f4(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_ServersType1(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, TrUserData).

skip_varint_ServersType1(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> skip_varint_ServersType1(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_varint_ServersType1(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_ServersType1(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_length_delimited_ServersType1(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> skip_length_delimited_ServersType1(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_length_delimited_ServersType1(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_ServersType1(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_group_ServersType1(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_ServersType1(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_32_ServersType1(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_ServersType1(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_64_ServersType1(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_ServersType1(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

decode_msg_ServerConnectionDetailsWrapper(Bin, TrUserData) -> dfp_read_field_def_ServerConnectionDetailsWrapper(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), id([], TrUserData), TrUserData).

dfp_read_field_def_ServerConnectionDetailsWrapper(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_ServerConnectionDetailsWrapper_f1(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_ServerConnectionDetailsWrapper(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_ServerConnectionDetailsWrapper_f2(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_ServerConnectionDetailsWrapper(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> d_field_ServerConnectionDetailsWrapper_details(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
dfp_read_field_def_ServerConnectionDetailsWrapper(<<>>, 0, 0, _, F@_1, F@_2, R1, TrUserData) -> #'ServerConnectionDetailsWrapper'{f1 = F@_1, f2 = F@_2, details = lists_reverse(R1, TrUserData)};
dfp_read_field_def_ServerConnectionDetailsWrapper(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dg_read_field_def_ServerConnectionDetailsWrapper(Other, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

dg_read_field_def_ServerConnectionDetailsWrapper(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 32 - 7 -> dg_read_field_def_ServerConnectionDetailsWrapper(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
dg_read_field_def_ServerConnectionDetailsWrapper(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> d_field_ServerConnectionDetailsWrapper_f1(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        16 -> d_field_ServerConnectionDetailsWrapper_f2(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        26 -> d_field_ServerConnectionDetailsWrapper_details(Rest, 0, 0, 0, F@_1, F@_2, F@_3, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_ServerConnectionDetailsWrapper(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                1 -> skip_64_ServerConnectionDetailsWrapper(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                2 -> skip_length_delimited_ServerConnectionDetailsWrapper(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                3 -> skip_group_ServerConnectionDetailsWrapper(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData);
                5 -> skip_32_ServerConnectionDetailsWrapper(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, TrUserData)
            end
    end;
dg_read_field_def_ServerConnectionDetailsWrapper(<<>>, 0, 0, _, F@_1, F@_2, R1, TrUserData) -> #'ServerConnectionDetailsWrapper'{f1 = F@_1, f2 = F@_2, details = lists_reverse(R1, TrUserData)}.

d_field_ServerConnectionDetailsWrapper_f1(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_ServerConnectionDetailsWrapper_f1(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_ServerConnectionDetailsWrapper_f1(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_ServerConnectionDetailsWrapper(RestF, 0, 0, F, NewFValue, F@_2, F@_3, TrUserData).

d_field_ServerConnectionDetailsWrapper_f2(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_ServerConnectionDetailsWrapper_f2(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_ServerConnectionDetailsWrapper_f2(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_ServerConnectionDetailsWrapper(RestF, 0, 0, F, F@_1, NewFValue, F@_3, TrUserData).

d_field_ServerConnectionDetailsWrapper_details(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> d_field_ServerConnectionDetailsWrapper_details(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
d_field_ServerConnectionDetailsWrapper_details(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_ServerDetails(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_ServerConnectionDetailsWrapper(RestF, 0, 0, F, F@_1, F@_2, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_ServerConnectionDetailsWrapper(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> skip_varint_ServerConnectionDetailsWrapper(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData);
skip_varint_ServerConnectionDetailsWrapper(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_ServerConnectionDetailsWrapper(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_length_delimited_ServerConnectionDetailsWrapper(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) when N < 57 -> skip_length_delimited_ServerConnectionDetailsWrapper(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, TrUserData);
skip_length_delimited_ServerConnectionDetailsWrapper(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_ServerConnectionDetailsWrapper(Rest2, 0, 0, F, F@_1, F@_2, F@_3, TrUserData).

skip_group_ServerConnectionDetailsWrapper(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_ServerConnectionDetailsWrapper(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, TrUserData).

skip_32_ServerConnectionDetailsWrapper(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_ServerConnectionDetailsWrapper(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

skip_64_ServerConnectionDetailsWrapper(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData) -> dfp_read_field_def_ServerConnectionDetailsWrapper(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, TrUserData).

decode_msg_ServersType2(Bin, TrUserData) -> dfp_read_field_def_ServersType2(Bin, 0, 0, 0, id([], TrUserData), id(undefined, TrUserData), TrUserData).

dfp_read_field_def_ServersType2(<<10, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_ServersType2_details_wrapper(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_ServersType2(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> d_field_ServersType2_port(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
dfp_read_field_def_ServersType2(<<>>, 0, 0, _, R1, F@_2, TrUserData) -> #'ServersType2'{details_wrapper = lists_reverse(R1, TrUserData), port = F@_2};
dfp_read_field_def_ServersType2(Other, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dg_read_field_def_ServersType2(Other, Z1, Z2, F, F@_1, F@_2, TrUserData).

dg_read_field_def_ServersType2(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 32 - 7 -> dg_read_field_def_ServersType2(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
dg_read_field_def_ServersType2(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_ServersType2_details_wrapper(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        16 -> d_field_ServersType2_port(Rest, 0, 0, 0, F@_1, F@_2, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_ServersType2(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                1 -> skip_64_ServersType2(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                2 -> skip_length_delimited_ServersType2(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                3 -> skip_group_ServersType2(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData);
                5 -> skip_32_ServersType2(Rest, 0, 0, Key bsr 3, F@_1, F@_2, TrUserData)
            end
    end;
dg_read_field_def_ServersType2(<<>>, 0, 0, _, R1, F@_2, TrUserData) -> #'ServersType2'{details_wrapper = lists_reverse(R1, TrUserData), port = F@_2}.

d_field_ServersType2_details_wrapper(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_ServersType2_details_wrapper(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_ServersType2_details_wrapper(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_ServerConnectionDetailsWrapper(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_ServersType2(RestF, 0, 0, F, cons(NewFValue, Prev, TrUserData), F@_2, TrUserData).

d_field_ServersType2_port(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> d_field_ServersType2_port(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
d_field_ServersType2_port(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_ServersType2(RestF, 0, 0, F, F@_1, NewFValue, TrUserData).

skip_varint_ServersType2(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> skip_varint_ServersType2(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData);
skip_varint_ServersType2(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_ServersType2(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_length_delimited_ServersType2(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) when N < 57 -> skip_length_delimited_ServersType2(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, TrUserData);
skip_length_delimited_ServersType2(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_ServersType2(Rest2, 0, 0, F, F@_1, F@_2, TrUserData).

skip_group_ServersType2(Bin, _, Z2, FNum, F@_1, F@_2, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_ServersType2(Rest, 0, Z2, FNum, F@_1, F@_2, TrUserData).

skip_32_ServersType2(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_ServersType2(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

skip_64_ServersType2(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, TrUserData) -> dfp_read_field_def_ServersType2(Rest, Z1, Z2, F, F@_1, F@_2, TrUserData).

decode_msg_TCPServerInfo(Bin, TrUserData) -> dfp_read_field_def_TCPServerInfo(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id([], TrUserData), id([], TrUserData), TrUserData).

dfp_read_field_def_TCPServerInfo(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) -> d_field_TCPServerInfo_f1(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
dfp_read_field_def_TCPServerInfo(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) -> d_field_TCPServerInfo_player_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
dfp_read_field_def_TCPServerInfo(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) -> d_field_TCPServerInfo_f3(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
dfp_read_field_def_TCPServerInfo(<<194, 1, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) -> d_field_TCPServerInfo_servers(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
dfp_read_field_def_TCPServerInfo(<<202, 1, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) -> d_field_TCPServerInfo_other_servers(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
dfp_read_field_def_TCPServerInfo(<<>>, 0, 0, _, F@_1, F@_2, F@_3, R1, R2, TrUserData) -> #'TCPServerInfo'{f1 = F@_1, player_id = F@_2, f3 = F@_3, servers = lists_reverse(R1, TrUserData), other_servers = lists_reverse(R2, TrUserData)};
dfp_read_field_def_TCPServerInfo(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) -> dg_read_field_def_TCPServerInfo(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData).

dg_read_field_def_TCPServerInfo(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) when N < 32 - 7 -> dg_read_field_def_TCPServerInfo(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
dg_read_field_def_TCPServerInfo(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> d_field_TCPServerInfo_f1(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
        16 -> d_field_TCPServerInfo_player_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
        24 -> d_field_TCPServerInfo_f3(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
        194 -> d_field_TCPServerInfo_servers(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
        202 -> d_field_TCPServerInfo_other_servers(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_TCPServerInfo(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
                1 -> skip_64_TCPServerInfo(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
                2 -> skip_length_delimited_TCPServerInfo(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
                3 -> skip_group_TCPServerInfo(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
                5 -> skip_32_TCPServerInfo(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData)
            end
    end;
dg_read_field_def_TCPServerInfo(<<>>, 0, 0, _, F@_1, F@_2, F@_3, R1, R2, TrUserData) -> #'TCPServerInfo'{f1 = F@_1, player_id = F@_2, f3 = F@_3, servers = lists_reverse(R1, TrUserData), other_servers = lists_reverse(R2, TrUserData)}.

d_field_TCPServerInfo_f1(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) when N < 57 -> d_field_TCPServerInfo_f1(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
d_field_TCPServerInfo_f1(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, F@_5, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_TCPServerInfo(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, F@_5, TrUserData).

d_field_TCPServerInfo_player_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) when N < 57 -> d_field_TCPServerInfo_player_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
d_field_TCPServerInfo_player_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, F@_5, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_TCPServerInfo(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, F@_5, TrUserData).

d_field_TCPServerInfo_f3(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) when N < 57 -> d_field_TCPServerInfo_f3(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
d_field_TCPServerInfo_f3(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, F@_5, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_TCPServerInfo(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, F@_5, TrUserData).

d_field_TCPServerInfo_servers(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) when N < 57 -> d_field_TCPServerInfo_servers(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
d_field_TCPServerInfo_servers(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, Prev, F@_5, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_ServersType1(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_TCPServerInfo(RestF, 0, 0, F, F@_1, F@_2, F@_3, cons(NewFValue, Prev, TrUserData), F@_5, TrUserData).

d_field_TCPServerInfo_other_servers(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) when N < 57 -> d_field_TCPServerInfo_other_servers(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
d_field_TCPServerInfo_other_servers(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_ServersType2(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_TCPServerInfo(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_TCPServerInfo(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) -> skip_varint_TCPServerInfo(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
skip_varint_TCPServerInfo(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) -> dfp_read_field_def_TCPServerInfo(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData).

skip_length_delimited_TCPServerInfo(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) when N < 57 -> skip_length_delimited_TCPServerInfo(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData);
skip_length_delimited_TCPServerInfo(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_TCPServerInfo(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData).

skip_group_TCPServerInfo(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_TCPServerInfo(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData).

skip_32_TCPServerInfo(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) -> dfp_read_field_def_TCPServerInfo(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData).

skip_64_TCPServerInfo(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData) -> dfp_read_field_def_TCPServerInfo(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, TrUserData).

decode_msg_TCPHello(Bin, TrUserData) -> dfp_read_field_def_TCPHello(Bin, 0, 0, 0, id(undefined, TrUserData), TrUserData).

dfp_read_field_def_TCPHello(<<16, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_TCPHello_player_id(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_TCPHello(<<>>, 0, 0, _, F@_1, _) -> #'TCPHello'{player_id = F@_1};
dfp_read_field_def_TCPHello(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_TCPHello(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_TCPHello(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_TCPHello(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_TCPHello(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        16 -> d_field_TCPHello_player_id(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_TCPHello(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_TCPHello(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_TCPHello(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_TCPHello(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_TCPHello(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_TCPHello(<<>>, 0, 0, _, F@_1, _) -> #'TCPHello'{player_id = F@_1}.

d_field_TCPHello_player_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_TCPHello_player_id(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_TCPHello_player_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_TCPHello(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_TCPHello(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_TCPHello(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_TCPHello(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_TCPHello(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_TCPHello(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_TCPHello(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_TCPHello(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_TCPHello(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_TCPHello(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_TCPHello(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_TCPHello(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_TCPHello(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_TCPHello(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_TCPHello(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_RecurringTCPResponse(Bin, TrUserData) -> dfp_read_field_def_RecurringTCPResponse(Bin, 0, 0, 0, id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), id(undefined, TrUserData), TrUserData).

dfp_read_field_def_RecurringTCPResponse(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_RecurringTCPResponse_f1(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_RecurringTCPResponse(<<16, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_RecurringTCPResponse_player_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_RecurringTCPResponse(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_RecurringTCPResponse_f3(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_RecurringTCPResponse(<<88, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> d_field_RecurringTCPResponse_f11(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dfp_read_field_def_RecurringTCPResponse(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #'RecurringTCPResponse'{f1 = F@_1, player_id = F@_2, f3 = F@_3, f11 = F@_4};
dfp_read_field_def_RecurringTCPResponse(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dg_read_field_def_RecurringTCPResponse(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

dg_read_field_def_RecurringTCPResponse(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 32 - 7 -> dg_read_field_def_RecurringTCPResponse(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
dg_read_field_def_RecurringTCPResponse(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> d_field_RecurringTCPResponse_f1(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        16 -> d_field_RecurringTCPResponse_player_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        24 -> d_field_RecurringTCPResponse_f3(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        88 -> d_field_RecurringTCPResponse_f11(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_RecurringTCPResponse(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                1 -> skip_64_RecurringTCPResponse(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                2 -> skip_length_delimited_RecurringTCPResponse(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                3 -> skip_group_RecurringTCPResponse(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData);
                5 -> skip_32_RecurringTCPResponse(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, TrUserData)
            end
    end;
dg_read_field_def_RecurringTCPResponse(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, _) -> #'RecurringTCPResponse'{f1 = F@_1, player_id = F@_2, f3 = F@_3, f11 = F@_4}.

d_field_RecurringTCPResponse_f1(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_RecurringTCPResponse_f1(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_RecurringTCPResponse_f1(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_RecurringTCPResponse(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, TrUserData).

d_field_RecurringTCPResponse_player_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_RecurringTCPResponse_player_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_RecurringTCPResponse_player_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_RecurringTCPResponse(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, TrUserData).

d_field_RecurringTCPResponse_f3(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_RecurringTCPResponse_f3(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_RecurringTCPResponse_f3(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_RecurringTCPResponse(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, TrUserData).

d_field_RecurringTCPResponse_f11(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> d_field_RecurringTCPResponse_f11(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
d_field_RecurringTCPResponse_f11(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:32/signed-native>> = <<(X bsl N + Acc):32/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_RecurringTCPResponse(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, TrUserData).

skip_varint_RecurringTCPResponse(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> skip_varint_RecurringTCPResponse(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_varint_RecurringTCPResponse(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_RecurringTCPResponse(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_length_delimited_RecurringTCPResponse(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) when N < 57 -> skip_length_delimited_RecurringTCPResponse(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData);
skip_length_delimited_RecurringTCPResponse(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_RecurringTCPResponse(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_group_RecurringTCPResponse(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_RecurringTCPResponse(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_32_RecurringTCPResponse(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_RecurringTCPResponse(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

skip_64_RecurringTCPResponse(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData) -> dfp_read_field_def_RecurringTCPResponse(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) when element(1, Prev) =:= element(1, New) -> merge_msgs(Prev, New, element(1, Prev), []).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []);
merge_msgs(Prev, New, Opts) when element(1, Prev) =:= element(1, New), is_list(Opts) -> merge_msgs(Prev, New, element(1, Prev), Opts).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'ServerDetails' -> merge_msg_ServerDetails(Prev, New, TrUserData);
        'ServersType1' -> merge_msg_ServersType1(Prev, New, TrUserData);
        'ServerConnectionDetailsWrapper' -> merge_msg_ServerConnectionDetailsWrapper(Prev, New, TrUserData);
        'ServersType2' -> merge_msg_ServersType2(Prev, New, TrUserData);
        'TCPServerInfo' -> merge_msg_TCPServerInfo(Prev, New, TrUserData);
        'TCPHello' -> merge_msg_TCPHello(Prev, New, TrUserData);
        'RecurringTCPResponse' -> merge_msg_RecurringTCPResponse(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_ServerDetails/3}).
merge_msg_ServerDetails(#'ServerDetails'{}, #'ServerDetails'{f1 = NFf1, f2 = NFf2, ip = NFip, port = NFport}, _) -> #'ServerDetails'{f1 = NFf1, f2 = NFf2, ip = NFip, port = NFport}.

-compile({nowarn_unused_function,merge_msg_ServersType1/3}).
merge_msg_ServersType1(#'ServersType1'{details = PFdetails, f2 = PFf2, f3 = PFf3, f4 = PFf4}, #'ServersType1'{details = NFdetails, f2 = NFf2, f3 = NFf3, f4 = NFf4}, TrUserData) ->
    #'ServersType1'{details =
                        if PFdetails /= undefined, NFdetails /= undefined -> 'erlang_++'(PFdetails, NFdetails, TrUserData);
                           PFdetails == undefined -> NFdetails;
                           NFdetails == undefined -> PFdetails
                        end,
                    f2 =
                        if NFf2 =:= undefined -> PFf2;
                           true -> NFf2
                        end,
                    f3 =
                        if NFf3 =:= undefined -> PFf3;
                           true -> NFf3
                        end,
                    f4 =
                        if NFf4 =:= undefined -> PFf4;
                           true -> NFf4
                        end}.

-compile({nowarn_unused_function,merge_msg_ServerConnectionDetailsWrapper/3}).
merge_msg_ServerConnectionDetailsWrapper(#'ServerConnectionDetailsWrapper'{details = PFdetails}, #'ServerConnectionDetailsWrapper'{f1 = NFf1, f2 = NFf2, details = NFdetails}, TrUserData) ->
    #'ServerConnectionDetailsWrapper'{f1 = NFf1, f2 = NFf2,
                                      details =
                                          if PFdetails /= undefined, NFdetails /= undefined -> 'erlang_++'(PFdetails, NFdetails, TrUserData);
                                             PFdetails == undefined -> NFdetails;
                                             NFdetails == undefined -> PFdetails
                                          end}.

-compile({nowarn_unused_function,merge_msg_ServersType2/3}).
merge_msg_ServersType2(#'ServersType2'{details_wrapper = PFdetails_wrapper}, #'ServersType2'{details_wrapper = NFdetails_wrapper, port = NFport}, TrUserData) ->
    #'ServersType2'{details_wrapper =
                        if PFdetails_wrapper /= undefined, NFdetails_wrapper /= undefined -> 'erlang_++'(PFdetails_wrapper, NFdetails_wrapper, TrUserData);
                           PFdetails_wrapper == undefined -> NFdetails_wrapper;
                           NFdetails_wrapper == undefined -> PFdetails_wrapper
                        end,
                    port = NFport}.

-compile({nowarn_unused_function,merge_msg_TCPServerInfo/3}).
merge_msg_TCPServerInfo(#'TCPServerInfo'{f1 = PFf1, servers = PFservers, other_servers = PFother_servers}, #'TCPServerInfo'{f1 = NFf1, player_id = NFplayer_id, f3 = NFf3, servers = NFservers, other_servers = NFother_servers}, TrUserData) ->
    #'TCPServerInfo'{f1 =
                         if NFf1 =:= undefined -> PFf1;
                            true -> NFf1
                         end,
                     player_id = NFplayer_id, f3 = NFf3,
                     servers =
                         if PFservers /= undefined, NFservers /= undefined -> 'erlang_++'(PFservers, NFservers, TrUserData);
                            PFservers == undefined -> NFservers;
                            NFservers == undefined -> PFservers
                         end,
                     other_servers =
                         if PFother_servers /= undefined, NFother_servers /= undefined -> 'erlang_++'(PFother_servers, NFother_servers, TrUserData);
                            PFother_servers == undefined -> NFother_servers;
                            NFother_servers == undefined -> PFother_servers
                         end}.

-compile({nowarn_unused_function,merge_msg_TCPHello/3}).
merge_msg_TCPHello(#'TCPHello'{}, #'TCPHello'{player_id = NFplayer_id}, _) -> #'TCPHello'{player_id = NFplayer_id}.

-compile({nowarn_unused_function,merge_msg_RecurringTCPResponse/3}).
merge_msg_RecurringTCPResponse(#'RecurringTCPResponse'{f1 = PFf1, player_id = PFplayer_id, f3 = PFf3, f11 = PFf11}, #'RecurringTCPResponse'{f1 = NFf1, player_id = NFplayer_id, f3 = NFf3, f11 = NFf11}, _) ->
    #'RecurringTCPResponse'{f1 =
                                if NFf1 =:= undefined -> PFf1;
                                   true -> NFf1
                                end,
                            player_id =
                                if NFplayer_id =:= undefined -> PFplayer_id;
                                   true -> NFplayer_id
                                end,
                            f3 =
                                if NFf3 =:= undefined -> PFf3;
                                   true -> NFf3
                                end,
                            f11 =
                                if NFf11 =:= undefined -> PFf11;
                                   true -> NFf11
                                end}.


verify_msg(Msg) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), []);
verify_msg(X) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []);
verify_msg(Msg, Opts) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), Opts);
verify_msg(X, _Opts) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'ServerDetails' -> v_msg_ServerDetails(Msg, [MsgName], TrUserData);
        'ServersType1' -> v_msg_ServersType1(Msg, [MsgName], TrUserData);
        'ServerConnectionDetailsWrapper' -> v_msg_ServerConnectionDetailsWrapper(Msg, [MsgName], TrUserData);
        'ServersType2' -> v_msg_ServersType2(Msg, [MsgName], TrUserData);
        'TCPServerInfo' -> v_msg_TCPServerInfo(Msg, [MsgName], TrUserData);
        'TCPHello' -> v_msg_TCPHello(Msg, [MsgName], TrUserData);
        'RecurringTCPResponse' -> v_msg_RecurringTCPResponse(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_ServerDetails/3}).
-dialyzer({nowarn_function,v_msg_ServerDetails/3}).
v_msg_ServerDetails(#'ServerDetails'{f1 = F1, f2 = F2, ip = F3, port = F4}, Path, TrUserData) ->
    v_type_int32(F1, [f1 | Path], TrUserData),
    v_type_int32(F2, [f2 | Path], TrUserData),
    v_type_string(F3, [ip | Path], TrUserData),
    v_type_int32(F4, [port | Path], TrUserData),
    ok;
v_msg_ServerDetails(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'ServerDetails'}, X, Path).

-compile({nowarn_unused_function,v_msg_ServersType1/3}).
-dialyzer({nowarn_function,v_msg_ServersType1/3}).
v_msg_ServersType1(#'ServersType1'{details = F1, f2 = F2, f3 = F3, f4 = F4}, Path, TrUserData) ->
    if is_list(F1) ->
           _ = [v_msg_ServerDetails(Elem, [details | Path], TrUserData) || Elem <- F1],
           ok;
       true -> mk_type_error({invalid_list_of, {msg, 'ServerDetails'}}, F1, [details | Path])
    end,
    if F2 == undefined -> ok;
       true -> v_type_int32(F2, [f2 | Path], TrUserData)
    end,
    if F3 == undefined -> ok;
       true -> v_type_int32(F3, [f3 | Path], TrUserData)
    end,
    if F4 == undefined -> ok;
       true -> v_type_int32(F4, [f4 | Path], TrUserData)
    end,
    ok;
v_msg_ServersType1(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'ServersType1'}, X, Path).

-compile({nowarn_unused_function,v_msg_ServerConnectionDetailsWrapper/3}).
-dialyzer({nowarn_function,v_msg_ServerConnectionDetailsWrapper/3}).
v_msg_ServerConnectionDetailsWrapper(#'ServerConnectionDetailsWrapper'{f1 = F1, f2 = F2, details = F3}, Path, TrUserData) ->
    v_type_int32(F1, [f1 | Path], TrUserData),
    v_type_int32(F2, [f2 | Path], TrUserData),
    if is_list(F3) ->
           _ = [v_msg_ServerDetails(Elem, [details | Path], TrUserData) || Elem <- F3],
           ok;
       true -> mk_type_error({invalid_list_of, {msg, 'ServerDetails'}}, F3, [details | Path])
    end,
    ok;
v_msg_ServerConnectionDetailsWrapper(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'ServerConnectionDetailsWrapper'}, X, Path).

-compile({nowarn_unused_function,v_msg_ServersType2/3}).
-dialyzer({nowarn_function,v_msg_ServersType2/3}).
v_msg_ServersType2(#'ServersType2'{details_wrapper = F1, port = F2}, Path, TrUserData) ->
    if is_list(F1) ->
           _ = [v_msg_ServerConnectionDetailsWrapper(Elem, [details_wrapper | Path], TrUserData) || Elem <- F1],
           ok;
       true -> mk_type_error({invalid_list_of, {msg, 'ServerConnectionDetailsWrapper'}}, F1, [details_wrapper | Path])
    end,
    v_type_int32(F2, [port | Path], TrUserData),
    ok;
v_msg_ServersType2(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'ServersType2'}, X, Path).

-compile({nowarn_unused_function,v_msg_TCPServerInfo/3}).
-dialyzer({nowarn_function,v_msg_TCPServerInfo/3}).
v_msg_TCPServerInfo(#'TCPServerInfo'{f1 = F1, player_id = F2, f3 = F3, servers = F4, other_servers = F5}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_int32(F1, [f1 | Path], TrUserData)
    end,
    v_type_int32(F2, [player_id | Path], TrUserData),
    v_type_int32(F3, [f3 | Path], TrUserData),
    if is_list(F4) ->
           _ = [v_msg_ServersType1(Elem, [servers | Path], TrUserData) || Elem <- F4],
           ok;
       true -> mk_type_error({invalid_list_of, {msg, 'ServersType1'}}, F4, [servers | Path])
    end,
    if is_list(F5) ->
           _ = [v_msg_ServersType2(Elem, [other_servers | Path], TrUserData) || Elem <- F5],
           ok;
       true -> mk_type_error({invalid_list_of, {msg, 'ServersType2'}}, F5, [other_servers | Path])
    end,
    ok;
v_msg_TCPServerInfo(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'TCPServerInfo'}, X, Path).

-compile({nowarn_unused_function,v_msg_TCPHello/3}).
-dialyzer({nowarn_function,v_msg_TCPHello/3}).
v_msg_TCPHello(#'TCPHello'{player_id = F1}, Path, TrUserData) ->
    v_type_int32(F1, [player_id | Path], TrUserData),
    ok;
v_msg_TCPHello(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'TCPHello'}, X, Path).

-compile({nowarn_unused_function,v_msg_RecurringTCPResponse/3}).
-dialyzer({nowarn_function,v_msg_RecurringTCPResponse/3}).
v_msg_RecurringTCPResponse(#'RecurringTCPResponse'{f1 = F1, player_id = F2, f3 = F3, f11 = F4}, Path, TrUserData) ->
    if F1 == undefined -> ok;
       true -> v_type_int32(F1, [f1 | Path], TrUserData)
    end,
    if F2 == undefined -> ok;
       true -> v_type_int32(F2, [player_id | Path], TrUserData)
    end,
    if F3 == undefined -> ok;
       true -> v_type_int32(F3, [f3 | Path], TrUserData)
    end,
    if F4 == undefined -> ok;
       true -> v_type_int32(F4, [f11 | Path], TrUserData)
    end,
    ok;
v_msg_RecurringTCPResponse(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'RecurringTCPResponse'}, X, Path).

-compile({nowarn_unused_function,v_type_int32/3}).
-dialyzer({nowarn_function,v_type_int32/3}).
v_type_int32(N, _Path, _TrUserData) when -2147483648 =< N, N =< 2147483647 -> ok;
v_type_int32(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, int32, signed, 32}, N, Path);
v_type_int32(X, Path, _TrUserData) -> mk_type_error({bad_integer, int32, signed, 32}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{msg, 'ServerDetails'},
      [#field{name = f1, fnum = 1, rnum = 2, type = int32, occurrence = required, opts = []},
       #field{name = f2, fnum = 2, rnum = 3, type = int32, occurrence = required, opts = []},
       #field{name = ip, fnum = 3, rnum = 4, type = string, occurrence = required, opts = []},
       #field{name = port, fnum = 4, rnum = 5, type = int32, occurrence = required, opts = []}]},
     {{msg, 'ServersType1'},
      [#field{name = details, fnum = 1, rnum = 2, type = {msg, 'ServerDetails'}, occurrence = repeated, opts = []},
       #field{name = f2, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []},
       #field{name = f3, fnum = 3, rnum = 4, type = int32, occurrence = optional, opts = []},
       #field{name = f4, fnum = 4, rnum = 5, type = int32, occurrence = optional, opts = []}]},
     {{msg, 'ServerConnectionDetailsWrapper'},
      [#field{name = f1, fnum = 1, rnum = 2, type = int32, occurrence = required, opts = []},
       #field{name = f2, fnum = 2, rnum = 3, type = int32, occurrence = required, opts = []},
       #field{name = details, fnum = 3, rnum = 4, type = {msg, 'ServerDetails'}, occurrence = repeated, opts = []}]},
     {{msg, 'ServersType2'}, [#field{name = details_wrapper, fnum = 1, rnum = 2, type = {msg, 'ServerConnectionDetailsWrapper'}, occurrence = repeated, opts = []}, #field{name = port, fnum = 2, rnum = 3, type = int32, occurrence = required, opts = []}]},
     {{msg, 'TCPServerInfo'},
      [#field{name = f1, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []},
       #field{name = player_id, fnum = 2, rnum = 3, type = int32, occurrence = required, opts = []},
       #field{name = f3, fnum = 3, rnum = 4, type = int32, occurrence = required, opts = []},
       #field{name = servers, fnum = 24, rnum = 5, type = {msg, 'ServersType1'}, occurrence = repeated, opts = []},
       #field{name = other_servers, fnum = 25, rnum = 6, type = {msg, 'ServersType2'}, occurrence = repeated, opts = []}]},
     {{msg, 'TCPHello'}, [#field{name = player_id, fnum = 2, rnum = 2, type = int32, occurrence = required, opts = []}]},
     {{msg, 'RecurringTCPResponse'},
      [#field{name = f1, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []},
       #field{name = player_id, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []},
       #field{name = f3, fnum = 3, rnum = 4, type = int32, occurrence = optional, opts = []},
       #field{name = f11, fnum = 11, rnum = 5, type = int32, occurrence = optional, opts = []}]}].


get_msg_names() -> ['ServerDetails', 'ServersType1', 'ServerConnectionDetailsWrapper', 'ServersType2', 'TCPServerInfo', 'TCPHello', 'RecurringTCPResponse'].


get_group_names() -> [].


get_msg_or_group_names() -> ['ServerDetails', 'ServersType1', 'ServerConnectionDetailsWrapper', 'ServersType2', 'TCPServerInfo', 'TCPHello', 'RecurringTCPResponse'].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) -> erlang:error({no_such_enum, EnumName}).


find_msg_def('ServerDetails') ->
    [#field{name = f1, fnum = 1, rnum = 2, type = int32, occurrence = required, opts = []},
     #field{name = f2, fnum = 2, rnum = 3, type = int32, occurrence = required, opts = []},
     #field{name = ip, fnum = 3, rnum = 4, type = string, occurrence = required, opts = []},
     #field{name = port, fnum = 4, rnum = 5, type = int32, occurrence = required, opts = []}];
find_msg_def('ServersType1') ->
    [#field{name = details, fnum = 1, rnum = 2, type = {msg, 'ServerDetails'}, occurrence = repeated, opts = []},
     #field{name = f2, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []},
     #field{name = f3, fnum = 3, rnum = 4, type = int32, occurrence = optional, opts = []},
     #field{name = f4, fnum = 4, rnum = 5, type = int32, occurrence = optional, opts = []}];
find_msg_def('ServerConnectionDetailsWrapper') ->
    [#field{name = f1, fnum = 1, rnum = 2, type = int32, occurrence = required, opts = []},
     #field{name = f2, fnum = 2, rnum = 3, type = int32, occurrence = required, opts = []},
     #field{name = details, fnum = 3, rnum = 4, type = {msg, 'ServerDetails'}, occurrence = repeated, opts = []}];
find_msg_def('ServersType2') ->
    [#field{name = details_wrapper, fnum = 1, rnum = 2, type = {msg, 'ServerConnectionDetailsWrapper'}, occurrence = repeated, opts = []}, #field{name = port, fnum = 2, rnum = 3, type = int32, occurrence = required, opts = []}];
find_msg_def('TCPServerInfo') ->
    [#field{name = f1, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []},
     #field{name = player_id, fnum = 2, rnum = 3, type = int32, occurrence = required, opts = []},
     #field{name = f3, fnum = 3, rnum = 4, type = int32, occurrence = required, opts = []},
     #field{name = servers, fnum = 24, rnum = 5, type = {msg, 'ServersType1'}, occurrence = repeated, opts = []},
     #field{name = other_servers, fnum = 25, rnum = 6, type = {msg, 'ServersType2'}, occurrence = repeated, opts = []}];
find_msg_def('TCPHello') -> [#field{name = player_id, fnum = 2, rnum = 2, type = int32, occurrence = required, opts = []}];
find_msg_def('RecurringTCPResponse') ->
    [#field{name = f1, fnum = 1, rnum = 2, type = int32, occurrence = optional, opts = []},
     #field{name = player_id, fnum = 2, rnum = 3, type = int32, occurrence = optional, opts = []},
     #field{name = f3, fnum = 3, rnum = 4, type = int32, occurrence = optional, opts = []},
     #field{name = f11, fnum = 11, rnum = 5, type = int32, occurrence = optional, opts = []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) -> erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) -> erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) -> erlang:error({no_such_rpc, ServiceName, RpcName}).


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"zwiftj.api.model.ServerDetails">>) -> 'ServerDetails';
fqbin_to_msg_name(<<"zwiftj.api.model.ServersType1">>) -> 'ServersType1';
fqbin_to_msg_name(<<"zwiftj.api.model.ServerConnectionDetailsWrapper">>) -> 'ServerConnectionDetailsWrapper';
fqbin_to_msg_name(<<"zwiftj.api.model.ServersType2">>) -> 'ServersType2';
fqbin_to_msg_name(<<"zwiftj.api.model.TCPServerInfo">>) -> 'TCPServerInfo';
fqbin_to_msg_name(<<"zwiftj.api.model.TCPHello">>) -> 'TCPHello';
fqbin_to_msg_name(<<"zwiftj.api.model.RecurringTCPResponse">>) -> 'RecurringTCPResponse';
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin('ServerDetails') -> <<"zwiftj.api.model.ServerDetails">>;
msg_name_to_fqbin('ServersType1') -> <<"zwiftj.api.model.ServersType1">>;
msg_name_to_fqbin('ServerConnectionDetailsWrapper') -> <<"zwiftj.api.model.ServerConnectionDetailsWrapper">>;
msg_name_to_fqbin('ServersType2') -> <<"zwiftj.api.model.ServersType2">>;
msg_name_to_fqbin('TCPServerInfo') -> <<"zwiftj.api.model.TCPServerInfo">>;
msg_name_to_fqbin('TCPHello') -> <<"zwiftj.api.model.TCPHello">>;
msg_name_to_fqbin('RecurringTCPResponse') -> <<"zwiftj.api.model.RecurringTCPResponse">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec fqbin_to_enum_name(_) -> no_return().
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


-spec enum_name_to_fqbin(_) -> no_return().
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> 'zwiftj.api.model'.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> false.


source_basename() -> "tcp-node-msgs.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["tcp-node-msgs.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["tcp-node-msgs"].


get_msg_containment("tcp-node-msgs") -> ['RecurringTCPResponse', 'ServerConnectionDetailsWrapper', 'ServerDetails', 'ServersType1', 'ServersType2', 'TCPHello', 'TCPServerInfo'];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("tcp-node-msgs") -> undefined;
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("tcp-node-msgs") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("tcp-node-msgs") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("tcp-node-msgs") -> [];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.ServersType1">>) -> "tcp-node-msgs";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.ServersType2">>) -> "tcp-node-msgs";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.ServerConnectionDetailsWrapper">>) -> "tcp-node-msgs";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.ServerDetails">>) -> "tcp-node-msgs";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.RecurringTCPResponse">>) -> "tcp-node-msgs";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.TCPServerInfo">>) -> "tcp-node-msgs";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.TCPHello">>) -> "tcp-node-msgs";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec get_proto_by_service_name_as_fqbin(_) -> no_return().
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


-spec get_proto_by_enum_name_as_fqbin(_) -> no_return().
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


-spec get_protos_by_pkg_name_as_fqbin(_) -> no_return().
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.18.0".

gpb_version_as_list() ->
    [4,18,0].

gpb_version_source() ->
    "file".
