%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.18.0
%% Version source: file
-module(world_pb).

-export([encode_msg/1, encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/2, merge_msgs/3, merge_msgs/4]).
-export([verify_msg/1, verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).
-export([gpb_version_source/0]).

-include("world_pb.hrl").
-include("gpb.hrl").

%% enumerated types

-export_type([]).

%% message types
-type 'World'() :: #'World'{}.

-type 'Worlds'() :: #'Worlds'{}.

-type 'WorldAttributes'() :: #'WorldAttributes'{}.

-type 'Player'() :: #'Player'{}.

-export_type(['World'/0, 'Worlds'/0, 'WorldAttributes'/0, 'Player'/0]).
-type '$msg_name'() :: 'World' | 'Worlds' | 'WorldAttributes' | 'Player'.
-type '$msg'() :: 'World'() | 'Worlds'() | 'WorldAttributes'() | 'Player'().
-export_type(['$msg_name'/0, '$msg'/0]).

-dialyzer({no_underspecs, encode_msg/1}).
-spec encode_msg('$msg'()) -> binary().
encode_msg(Msg) when tuple_size(Msg) >= 1 -> encode_msg(Msg, element(1, Msg), []).

-dialyzer({no_underspecs, encode_msg/2}).
-spec encode_msg('$msg'(), '$msg_name'() | list()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) -> encode_msg(Msg, MsgName, []);
encode_msg(Msg, Opts) when tuple_size(Msg) >= 1, is_list(Opts) -> encode_msg(Msg, element(1, Msg), Opts).

-dialyzer({no_underspecs, encode_msg/3}).
-spec encode_msg('$msg'(), '$msg_name'(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'World' -> encode_msg_World(id(Msg, TrUserData), TrUserData);
        'Worlds' -> encode_msg_Worlds(id(Msg, TrUserData), TrUserData);
        'WorldAttributes' -> encode_msg_WorldAttributes(id(Msg, TrUserData), TrUserData);
        'Player' -> encode_msg_Player(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_World(Msg, TrUserData) -> encode_msg_World(Msg, <<>>, TrUserData).


encode_msg_World(#'World'{id = F1, name = F2, f3 = F3, f5 = F4, world_time = F5, real_time = F6, player_states = F7, pace_partner_states = F8}, Bin, TrUserData) ->
    B1 = begin TrF1 = id(F1, TrUserData), e_varint(TrF1, <<Bin/binary, 8>>, TrUserData) end,
    B2 = begin TrF2 = id(F2, TrUserData), e_type_string(TrF2, <<B1/binary, 18>>, TrUserData) end,
    B3 = begin TrF3 = id(F3, TrUserData), e_varint(TrF3, <<B2/binary, 24>>, TrUserData) end,
    B4 = begin TrF4 = id(F4, TrUserData), e_varint(TrF4, <<B3/binary, 40>>, TrUserData) end,
    B5 = begin TrF5 = id(F5, TrUserData), e_varint(TrF5, <<B4/binary, 48>>, TrUserData) end,
    B6 = begin TrF6 = id(F6, TrUserData), e_varint(TrF6, <<B5/binary, 56>>, TrUserData) end,
    B7 = begin
             TrF7 = id(F7, TrUserData),
             if TrF7 == [] -> B6;
                true -> e_field_World_player_states(TrF7, B6, TrUserData)
             end
         end,
    begin
        TrF8 = id(F8, TrUserData),
        if TrF8 == [] -> B7;
           true -> e_field_World_pace_partner_states(TrF8, B7, TrUserData)
        end
    end.

encode_msg_Worlds(Msg, TrUserData) -> encode_msg_Worlds(Msg, <<>>, TrUserData).


encode_msg_Worlds(#'Worlds'{worlds = F1}, Bin, TrUserData) ->
    begin
        TrF1 = id(F1, TrUserData),
        if TrF1 == [] -> Bin;
           true -> e_field_Worlds_worlds(TrF1, Bin, TrUserData)
        end
    end.

encode_msg_WorldAttributes(Msg, TrUserData) -> encode_msg_WorldAttributes(Msg, <<>>, TrUserData).


encode_msg_WorldAttributes(#'WorldAttributes'{world_time = F1}, Bin, TrUserData) -> begin TrF1 = id(F1, TrUserData), e_type_int64(TrF1, <<Bin/binary, 16>>, TrUserData) end.

encode_msg_Player(Msg, TrUserData) -> encode_msg_Player(Msg, <<>>, TrUserData).


encode_msg_Player(#'Player'{id = F1, firstName = F2, lastName = F3, distance = F4, time = F5, f6 = F6, f8 = F7, f9 = F8, f10 = F9, f11 = F10, power = F11, f13 = F12, x = F13, altitude = F14, y = F15}, Bin, TrUserData) ->
    B1 = begin TrF1 = id(F1, TrUserData), e_varint(TrF1, <<Bin/binary, 8>>, TrUserData) end,
    B2 = begin TrF2 = id(F2, TrUserData), e_type_string(TrF2, <<B1/binary, 18>>, TrUserData) end,
    B3 = begin TrF3 = id(F3, TrUserData), e_type_string(TrF3, <<B2/binary, 26>>, TrUserData) end,
    B4 = if F4 == undefined -> B3;
            true -> begin TrF4 = id(F4, TrUserData), e_varint(TrF4, <<B3/binary, 32>>, TrUserData) end
         end,
    B5 = if F5 == undefined -> B4;
            true -> begin TrF5 = id(F5, TrUserData), e_varint(TrF5, <<B4/binary, 40>>, TrUserData) end
         end,
    B6 = if F6 == undefined -> B5;
            true -> begin TrF6 = id(F6, TrUserData), e_varint(TrF6, <<B5/binary, 48>>, TrUserData) end
         end,
    B7 = if F7 == undefined -> B6;
            true -> begin TrF7 = id(F7, TrUserData), e_varint(TrF7, <<B6/binary, 64>>, TrUserData) end
         end,
    B8 = if F8 == undefined -> B7;
            true -> begin TrF8 = id(F8, TrUserData), e_varint(TrF8, <<B7/binary, 72>>, TrUserData) end
         end,
    B9 = if F9 == undefined -> B8;
            true -> begin TrF9 = id(F9, TrUserData), e_varint(TrF9, <<B8/binary, 80>>, TrUserData) end
         end,
    B10 = if F10 == undefined -> B9;
             true -> begin TrF10 = id(F10, TrUserData), e_varint(TrF10, <<B9/binary, 88>>, TrUserData) end
          end,
    B11 = if F11 == undefined -> B10;
             true -> begin TrF11 = id(F11, TrUserData), e_varint(TrF11, <<B10/binary, 96>>, TrUserData) end
          end,
    B12 = if F12 == undefined -> B11;
             true -> begin TrF12 = id(F12, TrUserData), e_varint(TrF12, <<B11/binary, 104>>, TrUserData) end
          end,
    B13 = if F13 == undefined -> B12;
             true -> begin TrF13 = id(F13, TrUserData), e_type_float(TrF13, <<B12/binary, 117>>, TrUserData) end
          end,
    B14 = if F14 == undefined -> B13;
             true -> begin TrF14 = id(F14, TrUserData), e_type_float(TrF14, <<B13/binary, 125>>, TrUserData) end
          end,
    if F15 == undefined -> B14;
       true -> begin TrF15 = id(F15, TrUserData), e_type_float(TrF15, <<B14/binary, 133, 1>>, TrUserData) end
    end.

e_mfield_World_player_states(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_Player(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_World_player_states([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 66>>,
    Bin3 = e_mfield_World_player_states(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_World_player_states(Rest, Bin3, TrUserData);
e_field_World_player_states([], Bin, _TrUserData) -> Bin.

e_mfield_World_pace_partner_states(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_Player(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_World_pace_partner_states([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 98>>,
    Bin3 = e_mfield_World_pace_partner_states(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_World_pace_partner_states(Rest, Bin3, TrUserData);
e_field_World_pace_partner_states([], Bin, _TrUserData) -> Bin.

e_mfield_Worlds_worlds(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_World(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_Worlds_worlds([Elem | Rest], Bin, TrUserData) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_Worlds_worlds(id(Elem, TrUserData), Bin2, TrUserData),
    e_field_Worlds_worlds(Rest, Bin3, TrUserData);
e_field_Worlds_worlds([], Bin, _TrUserData) -> Bin.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 -> e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) -> e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData) when 0 =< Value, Value =< 127 -> <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) -> <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData) when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData) when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) -> <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) -> <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) -> <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) -> <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) -> <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) -> <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) -> <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) -> <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) -> <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) -> <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_unknown_elems/2}).
e_unknown_elems([Elem | Rest], Bin) ->
    BinR = case Elem of
               {varint, FNum, N} ->
                   BinF = e_varint(FNum bsl 3, Bin),
                   e_varint(N, BinF);
               {length_delimited, FNum, Data} ->
                   BinF = e_varint(FNum bsl 3 bor 2, Bin),
                   BinL = e_varint(byte_size(Data), BinF),
                   <<BinL/binary, Data/binary>>;
               {group, FNum, GroupFields} ->
                   Bin1 = e_varint(FNum bsl 3 bor 3, Bin),
                   Bin2 = e_unknown_elems(GroupFields, Bin1),
                   e_varint(FNum bsl 3 bor 4, Bin2);
               {fixed32, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 5, Bin),
                   <<BinF/binary, V:32/little>>;
               {fixed64, FNum, V} ->
                   BinF = e_varint(FNum bsl 3 bor 1, Bin),
                   <<BinF/binary, V:64/little>>
           end,
    e_unknown_elems(Rest, BinR);
e_unknown_elems([], Bin) -> Bin.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).


decode_msg(Bin, MsgName) when is_binary(Bin) -> decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason:StackTrace ->
            erlang:raise(error, Reason, StackTrace);
        Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch
        error:{gpb_error,_}=Reason ->
            erlang:raise(error, Reason,
                         erlang:get_stacktrace());
        Class:Reason ->
            StackTrace = erlang:get_stacktrace(),
            error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit('World', Bin, TrUserData) -> id(decode_msg_World(Bin, TrUserData), TrUserData);
decode_msg_2_doit('Worlds', Bin, TrUserData) -> id(decode_msg_Worlds(Bin, TrUserData), TrUserData);
decode_msg_2_doit('WorldAttributes', Bin, TrUserData) -> id(decode_msg_WorldAttributes(Bin, TrUserData), TrUserData);
decode_msg_2_doit('Player', Bin, TrUserData) -> id(decode_msg_Player(Bin, TrUserData), TrUserData).



decode_msg_World(Bin, TrUserData) ->
    dfp_read_field_def_World(Bin,
                             0,
                             0,
                             0,
                             id(undefined, TrUserData),
                             id(undefined, TrUserData),
                             id(undefined, TrUserData),
                             id(undefined, TrUserData),
                             id(undefined, TrUserData),
                             id(undefined, TrUserData),
                             id([], TrUserData),
                             id([], TrUserData),
                             TrUserData).

dfp_read_field_def_World(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> d_field_World_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_World(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> d_field_World_name(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_World(<<24, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> d_field_World_f3(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_World(<<40, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> d_field_World_f5(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_World(<<48, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> d_field_World_world_time(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_World(<<56, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> d_field_World_real_time(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_World(<<66, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> d_field_World_player_states(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_World(<<98, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> d_field_World_pace_partner_states(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dfp_read_field_def_World(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, R1, R2, TrUserData) ->
    #'World'{id = F@_1, name = F@_2, f3 = F@_3, f5 = F@_4, world_time = F@_5, real_time = F@_6, player_states = lists_reverse(R1, TrUserData), pace_partner_states = lists_reverse(R2, TrUserData)};
dfp_read_field_def_World(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> dg_read_field_def_World(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData).

dg_read_field_def_World(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_World(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
dg_read_field_def_World(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> d_field_World_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
        18 -> d_field_World_name(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
        24 -> d_field_World_f3(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
        40 -> d_field_World_f5(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
        48 -> d_field_World_world_time(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
        56 -> d_field_World_real_time(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
        66 -> d_field_World_player_states(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
        98 -> d_field_World_pace_partner_states(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_World(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
                1 -> skip_64_World(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
                2 -> skip_length_delimited_World(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
                3 -> skip_group_World(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
                5 -> skip_32_World(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData)
            end
    end;
dg_read_field_def_World(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, R1, R2, TrUserData) ->
    #'World'{id = F@_1, name = F@_2, f3 = F@_3, f5 = F@_4, world_time = F@_5, real_time = F@_6, player_states = lists_reverse(R1, TrUserData), pace_partner_states = lists_reverse(R2, TrUserData)}.

d_field_World_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) when N < 57 -> d_field_World_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
d_field_World_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_World(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData).

d_field_World_name(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) when N < 57 -> d_field_World_name(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
d_field_World_name(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_World(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData).

d_field_World_f3(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) when N < 57 -> d_field_World_f3(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
d_field_World_f3(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_World(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData).

d_field_World_f5(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) when N < 57 -> d_field_World_f5(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
d_field_World_f5(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, F@_5, F@_6, F@_7, F@_8, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 18446744073709551615, TrUserData), Rest},
    dfp_read_field_def_World(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, F@_5, F@_6, F@_7, F@_8, TrUserData).

d_field_World_world_time(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) when N < 57 ->
    d_field_World_world_time(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
d_field_World_world_time(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, _, F@_6, F@_7, F@_8, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 18446744073709551615, TrUserData), Rest},
    dfp_read_field_def_World(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, NewFValue, F@_6, F@_7, F@_8, TrUserData).

d_field_World_real_time(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) when N < 57 ->
    d_field_World_real_time(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
d_field_World_real_time(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, _, F@_7, F@_8, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 18446744073709551615, TrUserData), Rest},
    dfp_read_field_def_World(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, NewFValue, F@_7, F@_8, TrUserData).

d_field_World_player_states(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) when N < 57 ->
    d_field_World_player_states(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
d_field_World_player_states(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, Prev, F@_8, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_Player(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_World(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, cons(NewFValue, Prev, TrUserData), F@_8, TrUserData).

d_field_World_pace_partner_states(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) when N < 57 ->
    d_field_World_pace_partner_states(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
d_field_World_pace_partner_states(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_Player(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_World(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_World(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> skip_varint_World(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
skip_varint_World(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> dfp_read_field_def_World(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData).

skip_length_delimited_World(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) when N < 57 ->
    skip_length_delimited_World(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData);
skip_length_delimited_World(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_World(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData).

skip_group_World(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_World(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData).

skip_32_World(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> dfp_read_field_def_World(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData).

skip_64_World(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData) -> dfp_read_field_def_World(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, TrUserData).

decode_msg_Worlds(Bin, TrUserData) -> dfp_read_field_def_Worlds(Bin, 0, 0, 0, id([], TrUserData), TrUserData).

dfp_read_field_def_Worlds(<<10, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_Worlds_worlds(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_Worlds(<<>>, 0, 0, _, R1, TrUserData) -> #'Worlds'{worlds = lists_reverse(R1, TrUserData)};
dfp_read_field_def_Worlds(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_Worlds(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_Worlds(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_Worlds(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_Worlds(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_Worlds_worlds(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_Worlds(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_Worlds(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_Worlds(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_Worlds(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_Worlds(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_Worlds(<<>>, 0, 0, _, R1, TrUserData) -> #'Worlds'{worlds = lists_reverse(R1, TrUserData)}.

d_field_Worlds_worlds(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_Worlds_worlds(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_Worlds_worlds(<<0:1, X:7, Rest/binary>>, N, Acc, F, Prev, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bs:Len/binary, Rest2/binary>> = Rest, {id(decode_msg_World(Bs, TrUserData), TrUserData), Rest2} end,
    dfp_read_field_def_Worlds(RestF, 0, 0, F, cons(NewFValue, Prev, TrUserData), TrUserData).

skip_varint_Worlds(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_Worlds(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_Worlds(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_Worlds(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_Worlds(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_Worlds(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_Worlds(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Worlds(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_Worlds(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_Worlds(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_Worlds(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_Worlds(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_Worlds(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_Worlds(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_WorldAttributes(Bin, TrUserData) -> dfp_read_field_def_WorldAttributes(Bin, 0, 0, 0, id(undefined, TrUserData), TrUserData).

dfp_read_field_def_WorldAttributes(<<16, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> d_field_WorldAttributes_world_time(Rest, Z1, Z2, F, F@_1, TrUserData);
dfp_read_field_def_WorldAttributes(<<>>, 0, 0, _, F@_1, _) -> #'WorldAttributes'{world_time = F@_1};
dfp_read_field_def_WorldAttributes(Other, Z1, Z2, F, F@_1, TrUserData) -> dg_read_field_def_WorldAttributes(Other, Z1, Z2, F, F@_1, TrUserData).

dg_read_field_def_WorldAttributes(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 32 - 7 -> dg_read_field_def_WorldAttributes(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
dg_read_field_def_WorldAttributes(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        16 -> d_field_WorldAttributes_world_time(Rest, 0, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_WorldAttributes(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                1 -> skip_64_WorldAttributes(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                2 -> skip_length_delimited_WorldAttributes(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                3 -> skip_group_WorldAttributes(Rest, 0, 0, Key bsr 3, F@_1, TrUserData);
                5 -> skip_32_WorldAttributes(Rest, 0, 0, Key bsr 3, F@_1, TrUserData)
            end
    end;
dg_read_field_def_WorldAttributes(<<>>, 0, 0, _, F@_1, _) -> #'WorldAttributes'{world_time = F@_1}.

d_field_WorldAttributes_world_time(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> d_field_WorldAttributes_world_time(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
d_field_WorldAttributes_world_time(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, TrUserData) ->
    {NewFValue, RestF} = {begin <<Res:64/signed-native>> = <<(X bsl N + Acc):64/unsigned-native>>, id(Res, TrUserData) end, Rest},
    dfp_read_field_def_WorldAttributes(RestF, 0, 0, F, NewFValue, TrUserData).

skip_varint_WorldAttributes(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> skip_varint_WorldAttributes(Rest, Z1, Z2, F, F@_1, TrUserData);
skip_varint_WorldAttributes(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_WorldAttributes(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_length_delimited_WorldAttributes(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) when N < 57 -> skip_length_delimited_WorldAttributes(Rest, N + 7, X bsl N + Acc, F, F@_1, TrUserData);
skip_length_delimited_WorldAttributes(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_WorldAttributes(Rest2, 0, 0, F, F@_1, TrUserData).

skip_group_WorldAttributes(Bin, _, Z2, FNum, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_WorldAttributes(Rest, 0, Z2, FNum, F@_1, TrUserData).

skip_32_WorldAttributes(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_WorldAttributes(Rest, Z1, Z2, F, F@_1, TrUserData).

skip_64_WorldAttributes(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, TrUserData) -> dfp_read_field_def_WorldAttributes(Rest, Z1, Z2, F, F@_1, TrUserData).

decode_msg_Player(Bin, TrUserData) ->
    dfp_read_field_def_Player(Bin,
                              0,
                              0,
                              0,
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              id(undefined, TrUserData),
                              TrUserData).

dfp_read_field_def_Player(<<8, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_id(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<18, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_firstName(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<26, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_lastName(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_distance(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<40, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_time(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<48, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_f6(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_f8(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<72, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_f9(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<80, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_f10(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<88, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_f11(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<96, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_power(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<104, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_f13(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<117, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_x(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<125, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_altitude(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<133, 1, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    d_field_Player_y(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dfp_read_field_def_Player(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, _) ->
    #'Player'{id = F@_1, firstName = F@_2, lastName = F@_3, distance = F@_4, time = F@_5, f6 = F@_6, f8 = F@_7, f9 = F@_8, f10 = F@_9, f11 = F@_10, power = F@_11, f13 = F@_12, x = F@_13, altitude = F@_14, y = F@_15};
dfp_read_field_def_Player(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    dg_read_field_def_Player(Other, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

dg_read_field_def_Player(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 32 - 7 ->
    dg_read_field_def_Player(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
dg_read_field_def_Player(<<0:1, X:7, Rest/binary>>, N, Acc, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        8 -> d_field_Player_id(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        18 -> d_field_Player_firstName(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        26 -> d_field_Player_lastName(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        32 -> d_field_Player_distance(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        40 -> d_field_Player_time(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        48 -> d_field_Player_f6(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        64 -> d_field_Player_f8(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        72 -> d_field_Player_f9(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        80 -> d_field_Player_f10(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        88 -> d_field_Player_f11(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        96 -> d_field_Player_power(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        104 -> d_field_Player_f13(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        117 -> d_field_Player_x(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        125 -> d_field_Player_altitude(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        133 -> d_field_Player_y(Rest, 0, 0, 0, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_Player(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
                1 -> skip_64_Player(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
                2 -> skip_length_delimited_Player(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
                3 -> skip_group_Player(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
                5 -> skip_32_Player(Rest, 0, 0, Key bsr 3, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData)
            end
    end;
dg_read_field_def_Player(<<>>, 0, 0, _, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, _) ->
    #'Player'{id = F@_1, firstName = F@_2, lastName = F@_3, distance = F@_4, time = F@_5, f6 = F@_6, f8 = F@_7, f9 = F@_8, f10 = F@_9, f11 = F@_10, power = F@_11, f13 = F@_12, x = F@_13, altitude = F@_14, y = F@_15}.

d_field_Player_id(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_id(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_id(<<0:1, X:7, Rest/binary>>, N, Acc, F, _, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_Player(RestF, 0, 0, F, NewFValue, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_firstName(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_firstName(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_firstName(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, _, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_Player(RestF, 0, 0, F, F@_1, NewFValue, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_lastName(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_lastName(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_lastName(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, _, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = begin Len = X bsl N + Acc, <<Bytes:Len/binary, Rest2/binary>> = Rest, Bytes2 = binary:copy(Bytes), {id(Bytes2, TrUserData), Rest2} end,
    dfp_read_field_def_Player(RestF, 0, 0, F, F@_1, F@_2, NewFValue, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_distance(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_distance(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_distance(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, _, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_Player(RestF, 0, 0, F, F@_1, F@_2, F@_3, NewFValue, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_time(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_time(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_time(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, _, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_Player(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, NewFValue, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_f6(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_f6(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_f6(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, _, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_Player(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, NewFValue, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_f8(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_f8(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_f8(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, _, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_Player(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, NewFValue, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_f9(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_f9(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_f9(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, _, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_Player(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, NewFValue, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_f10(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_f10(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_f10(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, _, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_Player(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, NewFValue, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_f11(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_f11(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_f11(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, _, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_Player(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, NewFValue, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_power(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_power(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_power(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, _, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_Player(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, NewFValue, F@_12, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_f13(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    d_field_Player_f13(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
d_field_Player_f13(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, _, F@_13, F@_14, F@_15, TrUserData) ->
    {NewFValue, RestF} = {id((X bsl N + Acc) band 4294967295, TrUserData), Rest},
    dfp_read_field_def_Player(RestF, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, NewFValue, F@_13, F@_14, F@_15, TrUserData).

d_field_Player_x(<<0:16, 128, 127, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, _, F@_14, F@_15, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, id(infinity, TrUserData), F@_14, F@_15, TrUserData);
d_field_Player_x(<<0:16, 128, 255, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, _, F@_14, F@_15, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, id('-infinity', TrUserData), F@_14, F@_15, TrUserData);
d_field_Player_x(<<_:16, 1:1, _:7, _:1, 127:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, _, F@_14, F@_15, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, id(nan, TrUserData), F@_14, F@_15, TrUserData);
d_field_Player_x(<<Value:32/little-float, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, _, F@_14, F@_15, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, id(Value, TrUserData), F@_14, F@_15, TrUserData).

d_field_Player_altitude(<<0:16, 128, 127, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, _, F@_15, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, id(infinity, TrUserData), F@_15, TrUserData);
d_field_Player_altitude(<<0:16, 128, 255, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, _, F@_15, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, id('-infinity', TrUserData), F@_15, TrUserData);
d_field_Player_altitude(<<_:16, 1:1, _:7, _:1, 127:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, _, F@_15, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, id(nan, TrUserData), F@_15, TrUserData);
d_field_Player_altitude(<<Value:32/little-float, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, _, F@_15, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, id(Value, TrUserData), F@_15, TrUserData).

d_field_Player_y(<<0:16, 128, 127, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, _, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, id(infinity, TrUserData), TrUserData);
d_field_Player_y(<<0:16, 128, 255, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, _, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, id('-infinity', TrUserData), TrUserData);
d_field_Player_y(<<_:16, 1:1, _:7, _:1, 127:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, _, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, id(nan, TrUserData), TrUserData);
d_field_Player_y(<<Value:32/little-float, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, _, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, id(Value, TrUserData), TrUserData).

skip_varint_Player(<<1:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    skip_varint_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
skip_varint_Player(<<0:1, _:7, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

skip_length_delimited_Player(<<1:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) when N < 57 ->
    skip_length_delimited_Player(Rest, N + 7, X bsl N + Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData);
skip_length_delimited_Player(<<0:1, X:7, Rest/binary>>, N, Acc, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Player(Rest2, 0, 0, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

skip_group_Player(Bin, _, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_Player(Rest, 0, Z2, FNum, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

skip_32_Player(<<_:32, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

skip_64_Player(<<_:64, Rest/binary>>, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData) ->
    dfp_read_field_def_Player(Rest, Z1, Z2, F, F@_1, F@_2, F@_3, F@_4, F@_5, F@_6, F@_7, F@_8, F@_9, F@_10, F@_11, F@_12, F@_13, F@_14, F@_15, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New) when element(1, Prev) =:= element(1, New) -> merge_msgs(Prev, New, element(1, Prev), []).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) -> merge_msgs(Prev, New, MsgName, []);
merge_msgs(Prev, New, Opts) when element(1, Prev) =:= element(1, New), is_list(Opts) -> merge_msgs(Prev, New, element(1, Prev), Opts).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'World' -> merge_msg_World(Prev, New, TrUserData);
        'Worlds' -> merge_msg_Worlds(Prev, New, TrUserData);
        'WorldAttributes' -> merge_msg_WorldAttributes(Prev, New, TrUserData);
        'Player' -> merge_msg_Player(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_World/3}).
merge_msg_World(#'World'{player_states = PFplayer_states, pace_partner_states = PFpace_partner_states},
                #'World'{id = NFid, name = NFname, f3 = NFf3, f5 = NFf5, world_time = NFworld_time, real_time = NFreal_time, player_states = NFplayer_states, pace_partner_states = NFpace_partner_states}, TrUserData) ->
    #'World'{id = NFid, name = NFname, f3 = NFf3, f5 = NFf5, world_time = NFworld_time, real_time = NFreal_time,
             player_states =
                 if PFplayer_states /= undefined, NFplayer_states /= undefined -> 'erlang_++'(PFplayer_states, NFplayer_states, TrUserData);
                    PFplayer_states == undefined -> NFplayer_states;
                    NFplayer_states == undefined -> PFplayer_states
                 end,
             pace_partner_states =
                 if PFpace_partner_states /= undefined, NFpace_partner_states /= undefined -> 'erlang_++'(PFpace_partner_states, NFpace_partner_states, TrUserData);
                    PFpace_partner_states == undefined -> NFpace_partner_states;
                    NFpace_partner_states == undefined -> PFpace_partner_states
                 end}.

-compile({nowarn_unused_function,merge_msg_Worlds/3}).
merge_msg_Worlds(#'Worlds'{worlds = PFworlds}, #'Worlds'{worlds = NFworlds}, TrUserData) ->
    #'Worlds'{worlds =
                  if PFworlds /= undefined, NFworlds /= undefined -> 'erlang_++'(PFworlds, NFworlds, TrUserData);
                     PFworlds == undefined -> NFworlds;
                     NFworlds == undefined -> PFworlds
                  end}.

-compile({nowarn_unused_function,merge_msg_WorldAttributes/3}).
merge_msg_WorldAttributes(#'WorldAttributes'{}, #'WorldAttributes'{world_time = NFworld_time}, _) -> #'WorldAttributes'{world_time = NFworld_time}.

-compile({nowarn_unused_function,merge_msg_Player/3}).
merge_msg_Player(#'Player'{distance = PFdistance, time = PFtime, f6 = PFf6, f8 = PFf8, f9 = PFf9, f10 = PFf10, f11 = PFf11, power = PFpower, f13 = PFf13, x = PFx, altitude = PFaltitude, y = PFy},
                 #'Player'{id = NFid, firstName = NFfirstName, lastName = NFlastName, distance = NFdistance, time = NFtime, f6 = NFf6, f8 = NFf8, f9 = NFf9, f10 = NFf10, f11 = NFf11, power = NFpower, f13 = NFf13, x = NFx, altitude = NFaltitude, y = NFy}, _) ->
    #'Player'{id = NFid, firstName = NFfirstName, lastName = NFlastName,
              distance =
                  if NFdistance =:= undefined -> PFdistance;
                     true -> NFdistance
                  end,
              time =
                  if NFtime =:= undefined -> PFtime;
                     true -> NFtime
                  end,
              f6 =
                  if NFf6 =:= undefined -> PFf6;
                     true -> NFf6
                  end,
              f8 =
                  if NFf8 =:= undefined -> PFf8;
                     true -> NFf8
                  end,
              f9 =
                  if NFf9 =:= undefined -> PFf9;
                     true -> NFf9
                  end,
              f10 =
                  if NFf10 =:= undefined -> PFf10;
                     true -> NFf10
                  end,
              f11 =
                  if NFf11 =:= undefined -> PFf11;
                     true -> NFf11
                  end,
              power =
                  if NFpower =:= undefined -> PFpower;
                     true -> NFpower
                  end,
              f13 =
                  if NFf13 =:= undefined -> PFf13;
                     true -> NFf13
                  end,
              x =
                  if NFx =:= undefined -> PFx;
                     true -> NFx
                  end,
              altitude =
                  if NFaltitude =:= undefined -> PFaltitude;
                     true -> NFaltitude
                  end,
              y =
                  if NFy =:= undefined -> PFy;
                     true -> NFy
                  end}.


verify_msg(Msg) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), []);
verify_msg(X) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName) when is_atom(MsgName) -> verify_msg(Msg, MsgName, []);
verify_msg(Msg, Opts) when tuple_size(Msg) >= 1 -> verify_msg(Msg, element(1, Msg), Opts);
verify_msg(X, _Opts) -> mk_type_error(not_a_known_message, X, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        'World' -> v_msg_World(Msg, [MsgName], TrUserData);
        'Worlds' -> v_msg_Worlds(Msg, [MsgName], TrUserData);
        'WorldAttributes' -> v_msg_WorldAttributes(Msg, [MsgName], TrUserData);
        'Player' -> v_msg_Player(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_World/3}).
-dialyzer({nowarn_function,v_msg_World/3}).
v_msg_World(#'World'{id = F1, name = F2, f3 = F3, f5 = F4, world_time = F5, real_time = F6, player_states = F7, pace_partner_states = F8}, Path, TrUserData) ->
    v_type_uint32(F1, [id | Path], TrUserData),
    v_type_string(F2, [name | Path], TrUserData),
    v_type_uint32(F3, [f3 | Path], TrUserData),
    v_type_uint64(F4, [f5 | Path], TrUserData),
    v_type_uint64(F5, [world_time | Path], TrUserData),
    v_type_uint64(F6, [real_time | Path], TrUserData),
    if is_list(F7) ->
           _ = [v_msg_Player(Elem, [player_states | Path], TrUserData) || Elem <- F7],
           ok;
       true -> mk_type_error({invalid_list_of, {msg, 'Player'}}, F7, [player_states | Path])
    end,
    if is_list(F8) ->
           _ = [v_msg_Player(Elem, [pace_partner_states | Path], TrUserData) || Elem <- F8],
           ok;
       true -> mk_type_error({invalid_list_of, {msg, 'Player'}}, F8, [pace_partner_states | Path])
    end,
    ok;
v_msg_World(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'World'}, X, Path).

-compile({nowarn_unused_function,v_msg_Worlds/3}).
-dialyzer({nowarn_function,v_msg_Worlds/3}).
v_msg_Worlds(#'Worlds'{worlds = F1}, Path, TrUserData) ->
    if is_list(F1) ->
           _ = [v_msg_World(Elem, [worlds | Path], TrUserData) || Elem <- F1],
           ok;
       true -> mk_type_error({invalid_list_of, {msg, 'World'}}, F1, [worlds | Path])
    end,
    ok;
v_msg_Worlds(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'Worlds'}, X, Path).

-compile({nowarn_unused_function,v_msg_WorldAttributes/3}).
-dialyzer({nowarn_function,v_msg_WorldAttributes/3}).
v_msg_WorldAttributes(#'WorldAttributes'{world_time = F1}, Path, TrUserData) ->
    v_type_int64(F1, [world_time | Path], TrUserData),
    ok;
v_msg_WorldAttributes(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'WorldAttributes'}, X, Path).

-compile({nowarn_unused_function,v_msg_Player/3}).
-dialyzer({nowarn_function,v_msg_Player/3}).
v_msg_Player(#'Player'{id = F1, firstName = F2, lastName = F3, distance = F4, time = F5, f6 = F6, f8 = F7, f9 = F8, f10 = F9, f11 = F10, power = F11, f13 = F12, x = F13, altitude = F14, y = F15}, Path, TrUserData) ->
    v_type_uint32(F1, [id | Path], TrUserData),
    v_type_string(F2, [firstName | Path], TrUserData),
    v_type_string(F3, [lastName | Path], TrUserData),
    if F4 == undefined -> ok;
       true -> v_type_uint32(F4, [distance | Path], TrUserData)
    end,
    if F5 == undefined -> ok;
       true -> v_type_uint32(F5, [time | Path], TrUserData)
    end,
    if F6 == undefined -> ok;
       true -> v_type_uint32(F6, [f6 | Path], TrUserData)
    end,
    if F7 == undefined -> ok;
       true -> v_type_uint32(F7, [f8 | Path], TrUserData)
    end,
    if F8 == undefined -> ok;
       true -> v_type_uint32(F8, [f9 | Path], TrUserData)
    end,
    if F9 == undefined -> ok;
       true -> v_type_uint32(F9, [f10 | Path], TrUserData)
    end,
    if F10 == undefined -> ok;
       true -> v_type_uint32(F10, [f11 | Path], TrUserData)
    end,
    if F11 == undefined -> ok;
       true -> v_type_uint32(F11, [power | Path], TrUserData)
    end,
    if F12 == undefined -> ok;
       true -> v_type_uint32(F12, [f13 | Path], TrUserData)
    end,
    if F13 == undefined -> ok;
       true -> v_type_float(F13, [x | Path], TrUserData)
    end,
    if F14 == undefined -> ok;
       true -> v_type_float(F14, [altitude | Path], TrUserData)
    end,
    if F15 == undefined -> ok;
       true -> v_type_float(F15, [y | Path], TrUserData)
    end,
    ok;
v_msg_Player(X, Path, _TrUserData) -> mk_type_error({expected_msg, 'Player'}, X, Path).

-compile({nowarn_unused_function,v_type_int64/3}).
-dialyzer({nowarn_function,v_type_int64/3}).
v_type_int64(N, _Path, _TrUserData) when -9223372036854775808 =< N, N =< 9223372036854775807 -> ok;
v_type_int64(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, int64, signed, 64}, N, Path);
v_type_int64(X, Path, _TrUserData) -> mk_type_error({bad_integer, int64, signed, 64}, X, Path).

-compile({nowarn_unused_function,v_type_uint32/3}).
-dialyzer({nowarn_function,v_type_uint32/3}).
v_type_uint32(N, _Path, _TrUserData) when 0 =< N, N =< 4294967295 -> ok;
v_type_uint32(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, uint32, unsigned, 32}, N, Path);
v_type_uint32(X, Path, _TrUserData) -> mk_type_error({bad_integer, uint32, unsigned, 32}, X, Path).

-compile({nowarn_unused_function,v_type_uint64/3}).
-dialyzer({nowarn_function,v_type_uint64/3}).
v_type_uint64(N, _Path, _TrUserData) when 0 =< N, N =< 18446744073709551615 -> ok;
v_type_uint64(N, Path, _TrUserData) when is_integer(N) -> mk_type_error({value_out_of_range, uint64, unsigned, 64}, N, Path);
v_type_uint64(X, Path, _TrUserData) -> mk_type_error({bad_integer, uint64, unsigned, 64}, X, Path).

-compile({nowarn_unused_function,v_type_float/3}).
-dialyzer({nowarn_function,v_type_float/3}).
v_type_float(N, _Path, _TrUserData) when is_float(N) -> ok;
v_type_float(N, _Path, _TrUserData) when is_integer(N) -> ok;
v_type_float(infinity, _Path, _TrUserData) -> ok;
v_type_float('-infinity', _Path, _TrUserData) -> ok;
v_type_float(nan, _Path, _TrUserData) -> ok;
v_type_float(X, Path, _TrUserData) -> mk_type_error(bad_float_value, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData) when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} -> mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg -> mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) -> mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error, {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) -> lists:append(lists:join(".", lists:map(fun atom_to_list/1, lists:reverse(PathR)))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{msg, 'World'},
      [#field{name = id, fnum = 1, rnum = 2, type = uint32, occurrence = required, opts = []},
       #field{name = name, fnum = 2, rnum = 3, type = string, occurrence = required, opts = []},
       #field{name = f3, fnum = 3, rnum = 4, type = uint32, occurrence = required, opts = []},
       #field{name = f5, fnum = 5, rnum = 5, type = uint64, occurrence = required, opts = []},
       #field{name = world_time, fnum = 6, rnum = 6, type = uint64, occurrence = required, opts = []},
       #field{name = real_time, fnum = 7, rnum = 7, type = uint64, occurrence = required, opts = []},
       #field{name = player_states, fnum = 8, rnum = 8, type = {msg, 'Player'}, occurrence = repeated, opts = []},
       #field{name = pace_partner_states, fnum = 12, rnum = 9, type = {msg, 'Player'}, occurrence = repeated, opts = []}]},
     {{msg, 'Worlds'}, [#field{name = worlds, fnum = 1, rnum = 2, type = {msg, 'World'}, occurrence = repeated, opts = []}]},
     {{msg, 'WorldAttributes'}, [#field{name = world_time, fnum = 2, rnum = 2, type = int64, occurrence = required, opts = []}]},
     {{msg, 'Player'},
      [#field{name = id, fnum = 1, rnum = 2, type = uint32, occurrence = required, opts = []},
       #field{name = firstName, fnum = 2, rnum = 3, type = string, occurrence = required, opts = []},
       #field{name = lastName, fnum = 3, rnum = 4, type = string, occurrence = required, opts = []},
       #field{name = distance, fnum = 4, rnum = 5, type = uint32, occurrence = optional, opts = []},
       #field{name = time, fnum = 5, rnum = 6, type = uint32, occurrence = optional, opts = []},
       #field{name = f6, fnum = 6, rnum = 7, type = uint32, occurrence = optional, opts = []},
       #field{name = f8, fnum = 8, rnum = 8, type = uint32, occurrence = optional, opts = []},
       #field{name = f9, fnum = 9, rnum = 9, type = uint32, occurrence = optional, opts = []},
       #field{name = f10, fnum = 10, rnum = 10, type = uint32, occurrence = optional, opts = []},
       #field{name = f11, fnum = 11, rnum = 11, type = uint32, occurrence = optional, opts = []},
       #field{name = power, fnum = 12, rnum = 12, type = uint32, occurrence = optional, opts = []},
       #field{name = f13, fnum = 13, rnum = 13, type = uint32, occurrence = optional, opts = []},
       #field{name = x, fnum = 14, rnum = 14, type = float, occurrence = optional, opts = []},
       #field{name = altitude, fnum = 15, rnum = 15, type = float, occurrence = optional, opts = []},
       #field{name = y, fnum = 16, rnum = 16, type = float, occurrence = optional, opts = []}]}].


get_msg_names() -> ['World', 'Worlds', 'WorldAttributes', 'Player'].


get_group_names() -> [].


get_msg_or_group_names() -> ['World', 'Worlds', 'WorldAttributes', 'Player'].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) -> erlang:error({no_such_enum, EnumName}).


find_msg_def('World') ->
    [#field{name = id, fnum = 1, rnum = 2, type = uint32, occurrence = required, opts = []},
     #field{name = name, fnum = 2, rnum = 3, type = string, occurrence = required, opts = []},
     #field{name = f3, fnum = 3, rnum = 4, type = uint32, occurrence = required, opts = []},
     #field{name = f5, fnum = 5, rnum = 5, type = uint64, occurrence = required, opts = []},
     #field{name = world_time, fnum = 6, rnum = 6, type = uint64, occurrence = required, opts = []},
     #field{name = real_time, fnum = 7, rnum = 7, type = uint64, occurrence = required, opts = []},
     #field{name = player_states, fnum = 8, rnum = 8, type = {msg, 'Player'}, occurrence = repeated, opts = []},
     #field{name = pace_partner_states, fnum = 12, rnum = 9, type = {msg, 'Player'}, occurrence = repeated, opts = []}];
find_msg_def('Worlds') -> [#field{name = worlds, fnum = 1, rnum = 2, type = {msg, 'World'}, occurrence = repeated, opts = []}];
find_msg_def('WorldAttributes') -> [#field{name = world_time, fnum = 2, rnum = 2, type = int64, occurrence = required, opts = []}];
find_msg_def('Player') ->
    [#field{name = id, fnum = 1, rnum = 2, type = uint32, occurrence = required, opts = []},
     #field{name = firstName, fnum = 2, rnum = 3, type = string, occurrence = required, opts = []},
     #field{name = lastName, fnum = 3, rnum = 4, type = string, occurrence = required, opts = []},
     #field{name = distance, fnum = 4, rnum = 5, type = uint32, occurrence = optional, opts = []},
     #field{name = time, fnum = 5, rnum = 6, type = uint32, occurrence = optional, opts = []},
     #field{name = f6, fnum = 6, rnum = 7, type = uint32, occurrence = optional, opts = []},
     #field{name = f8, fnum = 8, rnum = 8, type = uint32, occurrence = optional, opts = []},
     #field{name = f9, fnum = 9, rnum = 9, type = uint32, occurrence = optional, opts = []},
     #field{name = f10, fnum = 10, rnum = 10, type = uint32, occurrence = optional, opts = []},
     #field{name = f11, fnum = 11, rnum = 11, type = uint32, occurrence = optional, opts = []},
     #field{name = power, fnum = 12, rnum = 12, type = uint32, occurrence = optional, opts = []},
     #field{name = f13, fnum = 13, rnum = 13, type = uint32, occurrence = optional, opts = []},
     #field{name = x, fnum = 14, rnum = 14, type = float, occurrence = optional, opts = []},
     #field{name = altitude, fnum = 15, rnum = 15, type = float, occurrence = optional, opts = []},
     #field{name = y, fnum = 16, rnum = 16, type = float, occurrence = optional, opts = []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) -> erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) -> erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) -> erlang:error({no_such_rpc, ServiceName, RpcName}).


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) -> error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) -> error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) -> error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"zwiftj.api.model.World">>) -> 'World';
fqbin_to_msg_name(<<"zwiftj.api.model.Worlds">>) -> 'Worlds';
fqbin_to_msg_name(<<"zwiftj.api.model.WorldAttributes">>) -> 'WorldAttributes';
fqbin_to_msg_name(<<"zwiftj.api.model.Player">>) -> 'Player';
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin('World') -> <<"zwiftj.api.model.World">>;
msg_name_to_fqbin('Worlds') -> <<"zwiftj.api.model.Worlds">>;
msg_name_to_fqbin('WorldAttributes') -> <<"zwiftj.api.model.WorldAttributes">>;
msg_name_to_fqbin('Player') -> <<"zwiftj.api.model.Player">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec fqbin_to_enum_name(_) -> no_return().
fqbin_to_enum_name(E) -> error({gpb_error, {badenum, E}}).


-spec enum_name_to_fqbin(_) -> no_return().
enum_name_to_fqbin(E) -> error({gpb_error, {badenum, E}}).


get_package_name() -> 'zwiftj.api.model'.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> false.


source_basename() -> "world.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["world.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["world"].


get_msg_containment("world") -> ['Player', 'World', 'WorldAttributes', 'Worlds'];
get_msg_containment(P) -> error({gpb_error, {badproto, P}}).


get_pkg_containment("world") -> undefined;
get_pkg_containment(P) -> error({gpb_error, {badproto, P}}).


get_service_containment("world") -> [];
get_service_containment(P) -> error({gpb_error, {badproto, P}}).


get_rpc_containment("world") -> [];
get_rpc_containment(P) -> error({gpb_error, {badproto, P}}).


get_enum_containment("world") -> [];
get_enum_containment(P) -> error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.Player">>) -> "world";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.Worlds">>) -> "world";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.WorldAttributes">>) -> "world";
get_proto_by_msg_name_as_fqbin(<<"zwiftj.api.model.World">>) -> "world";
get_proto_by_msg_name_as_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec get_proto_by_service_name_as_fqbin(_) -> no_return().
get_proto_by_service_name_as_fqbin(E) -> error({gpb_error, {badservice, E}}).


-spec get_proto_by_enum_name_as_fqbin(_) -> no_return().
get_proto_by_enum_name_as_fqbin(E) -> error({gpb_error, {badenum, E}}).


-spec get_protos_by_pkg_name_as_fqbin(_) -> no_return().
get_protos_by_pkg_name_as_fqbin(E) -> error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.18.0".

gpb_version_as_list() ->
    [4,18,0].

gpb_version_source() ->
    "file".
